// this file was auto-generated by wrapit v1.6.0
#include "Wrapper.h"

#include "jlMinuit2.h"
#include "dbg_msg.h"
#include "jlcxx/functions.hpp"
#include "jlcxx/stl.hpp"
// Class generating the wrapper for type 
// signature to use in the veto file: 
struct JlGlobal: public Wrapper {

  JlGlobal(jlcxx::Module& jlModule): Wrapper(jlModule){
  }

  void add_methods() const{
    auto& t = module_;

    DEBUG_MSG("Adding wrapper for int ROOT::Minuit2::Mndaxpy(unsigned int, double, const double *, int, double *, int) (" __HERE__ ")");
    // signature to use in the veto list: int ROOT::Minuit2::Mndaxpy(unsigned int, double, const double *, int, double *, int)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/LAVector.h:28:5
    t.method("ROOT!Minuit2!Mndaxpy", [](unsigned int arg0, double arg1, const double * arg2, int arg3, double * arg4, int arg5)->int { return ROOT::Minuit2::Mndaxpy(arg0, arg1, arg2, arg3, arg4, arg5); }, jlcxx::arg("this"), jlcxx::arg("arg0"), jlcxx::arg("arg1"), jlcxx::arg("arg2"), jlcxx::arg("arg3"), jlcxx::arg("arg4"), jlcxx::arg("arg5"));

    DEBUG_MSG("Adding wrapper for int ROOT::Minuit2::Mndscal(unsigned int, double, double *, int) (" __HERE__ ")");
    // signature to use in the veto list: int ROOT::Minuit2::Mndscal(unsigned int, double, double *, int)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/LAVector.h:29:5
    t.method("ROOT!Minuit2!Mndscal", [](unsigned int arg0, double arg1, double * arg2, int arg3)->int { return ROOT::Minuit2::Mndscal(arg0, arg1, arg2, arg3); }, jlcxx::arg("this"), jlcxx::arg("arg0"), jlcxx::arg("arg1"), jlcxx::arg("arg2"), jlcxx::arg("arg3"));

    DEBUG_MSG("Adding wrapper for int ROOT::Minuit2::Mndspmv(const char *, unsigned int, double, const double *, const double *, int, double, double *, int) (" __HERE__ ")");
    // signature to use in the veto list: int ROOT::Minuit2::Mndspmv(const char *, unsigned int, double, const double *, const double *, int, double, double *, int)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/LAVector.h:30:5
    t.method("ROOT!Minuit2!Mndspmv", [](const char * arg0, unsigned int arg1, double arg2, const double * arg3, const double * arg4, int arg5, double arg6, double * arg7, int arg8)->int { return ROOT::Minuit2::Mndspmv(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8); }, jlcxx::arg("this"), jlcxx::arg("arg0"), jlcxx::arg("arg1"), jlcxx::arg("arg2"), jlcxx::arg("arg3"), jlcxx::arg("arg4"), jlcxx::arg("arg5"), jlcxx::arg("arg6"), jlcxx::arg("arg7"), jlcxx::arg("arg8"));

    DEBUG_MSG("Adding wrapper for int NIter(const ROOT::Minuit2::FunctionMinimum &) (" __HERE__ ")");
    // signature to use in the veto list: int NIter(const ROOT::Minuit2::FunctionMinimum &)
    // defined in cpp/Minuit2Wrap.h:48:12
    t.method("NIter", [](const ROOT::Minuit2::FunctionMinimum & arg0)->int { return NIter(arg0); }, jlcxx::arg("this"), jlcxx::arg("min"));

    DEBUG_MSG("Adding wrapper for ROOT::Minuit2::FunctionMinimum ROOT::Minuit2::createFunctionMinimum(const JuliaFcn &, const ROOT::Minuit2::MnUserParameterState &, const ROOT::Minuit2::MnStrategy &, double) (" __HERE__ ")");
    // signature to use in the veto list: ROOT::Minuit2::FunctionMinimum ROOT::Minuit2::createFunctionMinimum(const JuliaFcn &, const ROOT::Minuit2::MnUserParameterState &, const ROOT::Minuit2::MnStrategy &, double)
    // defined in cpp/Minuit2Wrap.h:55:21
    t.method("ROOT!Minuit2!createFunctionMinimum", [](const JuliaFcn & arg0, const ROOT::Minuit2::MnUserParameterState & arg1, const ROOT::Minuit2::MnStrategy & arg2, double arg3)->ROOT::Minuit2::FunctionMinimum { return ROOT::Minuit2::createFunctionMinimum(arg0, arg1, arg2, arg3); }, jlcxx::arg("this"), jlcxx::arg("fcn"), jlcxx::arg("st"), jlcxx::arg("str"), jlcxx::arg("edm_goal"));

    DEBUG_MSG("Adding wrapper for ROOT::Minuit2::MnUserParameterState ROOT::Minuit2::createMnUserParameterState(const ROOT::Minuit2::MnUserParameterState &) (" __HERE__ ")");
    // signature to use in the veto list: ROOT::Minuit2::MnUserParameterState ROOT::Minuit2::createMnUserParameterState(const ROOT::Minuit2::MnUserParameterState &)
    // defined in cpp/Minuit2Wrap.h:57:26
    t.method("ROOT!Minuit2!createMnUserParameterState", [](const ROOT::Minuit2::MnUserParameterState & arg0)->ROOT::Minuit2::MnUserParameterState { return ROOT::Minuit2::createMnUserParameterState(arg0); }, jlcxx::arg("this"), jlcxx::arg("state"));

    DEBUG_MSG("Adding wrapper for std::vector<XYPoint> paren(const ROOT::Minuit2::MnContours &, unsigned int, unsigned int, unsigned int) (" __HERE__ ")");
    // signature to use in the veto list: std::vector<XYPoint> paren(const ROOT::Minuit2::MnContours &, unsigned int, unsigned int, unsigned int)
    // defined in cpp/Minuit2Wrap.h:74:22
    t.method("paren", [](const ROOT::Minuit2::MnContours & arg0, unsigned int arg1, unsigned int arg2, unsigned int arg3)->std::vector<XYPoint> { return paren(arg0, arg1, arg2, arg3); }, jlcxx::arg("this"), jlcxx::arg("contour"), jlcxx::arg("i"), jlcxx::arg("j"), jlcxx::arg("npoints"));

    DEBUG_MSG("Adding ROOT!Minuit2!MnPrint!eError methods to provide access to the global variable ROOT::Minuit2::MnPrint::eError (" __HERE__ ")");
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnPrint.h:79:26
    module_.method("ROOT!Minuit2!MnPrint!eError", []()-> ROOT::Minuit2::MnPrint::Verbosity { return ROOT::Minuit2::MnPrint::eError; });

    DEBUG_MSG("Adding ROOT!Minuit2!MnPrint!eWarn methods to provide access to the global variable ROOT::Minuit2::MnPrint::eWarn (" __HERE__ ")");
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnPrint.h:80:26
    module_.method("ROOT!Minuit2!MnPrint!eWarn", []()-> ROOT::Minuit2::MnPrint::Verbosity { return ROOT::Minuit2::MnPrint::eWarn; });

    DEBUG_MSG("Adding ROOT!Minuit2!MnPrint!eInfo methods to provide access to the global variable ROOT::Minuit2::MnPrint::eInfo (" __HERE__ ")");
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnPrint.h:81:26
    module_.method("ROOT!Minuit2!MnPrint!eInfo", []()-> ROOT::Minuit2::MnPrint::Verbosity { return ROOT::Minuit2::MnPrint::eInfo; });

    DEBUG_MSG("Adding ROOT!Minuit2!MnPrint!eDebug methods to provide access to the global variable ROOT::Minuit2::MnPrint::eDebug (" __HERE__ ")");
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnPrint.h:82:26
    module_.method("ROOT!Minuit2!MnPrint!eDebug", []()-> ROOT::Minuit2::MnPrint::Verbosity { return ROOT::Minuit2::MnPrint::eDebug; });

    DEBUG_MSG("Adding ROOT!Minuit2!MnPrint!eTrace methods to provide access to the global variable ROOT::Minuit2::MnPrint::eTrace (" __HERE__ ")");
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnPrint.h:83:26
    module_.method("ROOT!Minuit2!MnPrint!eTrace", []()-> ROOT::Minuit2::MnPrint::Verbosity { return ROOT::Minuit2::MnPrint::eTrace; });
  }
};
std::shared_ptr<Wrapper> newJlGlobal(jlcxx::Module& module){
  return std::shared_ptr<Wrapper>(new JlGlobal(module));
}
