// this file was auto-generated by wrapit 5168a24-dirty
#include "Wrapper.h"

#include "jlMinuit2.h"
#include "dbg_msg.h"
#include "jlcxx/functions.hpp"
#include "jlcxx/stl.hpp"

namespace jlcxx {
  template<> struct IsMirroredType<ROOT::Minuit2::MnStrategy> : std::false_type { };
  template<> struct DefaultConstructible<ROOT::Minuit2::MnStrategy> : std::false_type { };
}

// Class generating the wrapper for type ROOT::Minuit2::MnStrategy
// signature to use in the veto file: ROOT::Minuit2::MnStrategy
struct JlROOT_Minuit2_MnStrategy: public Wrapper {

  JlROOT_Minuit2_MnStrategy(jlcxx::Module& jlModule): Wrapper(jlModule){
    DEBUG_MSG("Adding wrapper for type ROOT::Minuit2::MnStrategy (" __HERE__ ")");
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnStrategy.h:27:7
    jlcxx::TypeWrapper<ROOT::Minuit2::MnStrategy>  t = jlModule.add_type<ROOT::Minuit2::MnStrategy>("ROOT!Minuit2!MnStrategy");
    type_ = std::unique_ptr<jlcxx::TypeWrapper<ROOT::Minuit2::MnStrategy>>(new jlcxx::TypeWrapper<ROOT::Minuit2::MnStrategy>(jlModule, t));
  }

  void add_methods() const{
    auto& t = *type_;
    t.template constructor<>(/*finalize=*/jlcxx::finalize_policy::yes);


    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnStrategy::MnStrategy(unsigned int) (" __HERE__ ")");
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnStrategy.h:34:13
    t.constructor<unsigned int>(/*finalize=*/jlcxx::finalize_policy::yes);

    DEBUG_MSG("Adding wrapper for unsigned int ROOT::Minuit2::MnStrategy::Strategy() (" __HERE__ ")");
    // signature to use in the veto list: unsigned int ROOT::Minuit2::MnStrategy::Strategy()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnStrategy.h:38:17
    t.method("Strategy", static_cast<unsigned int (ROOT::Minuit2::MnStrategy::*)()  const>(&ROOT::Minuit2::MnStrategy::Strategy));

    DEBUG_MSG("Adding wrapper for unsigned int ROOT::Minuit2::MnStrategy::GradientNCycles() (" __HERE__ ")");
    // signature to use in the veto list: unsigned int ROOT::Minuit2::MnStrategy::GradientNCycles()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnStrategy.h:40:17
    t.method("GradientNCycles", static_cast<unsigned int (ROOT::Minuit2::MnStrategy::*)()  const>(&ROOT::Minuit2::MnStrategy::GradientNCycles));

    DEBUG_MSG("Adding wrapper for double ROOT::Minuit2::MnStrategy::GradientStepTolerance() (" __HERE__ ")");
    // signature to use in the veto list: double ROOT::Minuit2::MnStrategy::GradientStepTolerance()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnStrategy.h:41:11
    t.method("GradientStepTolerance", static_cast<double (ROOT::Minuit2::MnStrategy::*)()  const>(&ROOT::Minuit2::MnStrategy::GradientStepTolerance));

    DEBUG_MSG("Adding wrapper for double ROOT::Minuit2::MnStrategy::GradientTolerance() (" __HERE__ ")");
    // signature to use in the veto list: double ROOT::Minuit2::MnStrategy::GradientTolerance()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnStrategy.h:42:11
    t.method("GradientTolerance", static_cast<double (ROOT::Minuit2::MnStrategy::*)()  const>(&ROOT::Minuit2::MnStrategy::GradientTolerance));

    DEBUG_MSG("Adding wrapper for unsigned int ROOT::Minuit2::MnStrategy::HessianNCycles() (" __HERE__ ")");
    // signature to use in the veto list: unsigned int ROOT::Minuit2::MnStrategy::HessianNCycles()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnStrategy.h:44:17
    t.method("HessianNCycles", static_cast<unsigned int (ROOT::Minuit2::MnStrategy::*)()  const>(&ROOT::Minuit2::MnStrategy::HessianNCycles));

    DEBUG_MSG("Adding wrapper for double ROOT::Minuit2::MnStrategy::HessianStepTolerance() (" __HERE__ ")");
    // signature to use in the veto list: double ROOT::Minuit2::MnStrategy::HessianStepTolerance()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnStrategy.h:45:11
    t.method("HessianStepTolerance", static_cast<double (ROOT::Minuit2::MnStrategy::*)()  const>(&ROOT::Minuit2::MnStrategy::HessianStepTolerance));

    DEBUG_MSG("Adding wrapper for double ROOT::Minuit2::MnStrategy::HessianG2Tolerance() (" __HERE__ ")");
    // signature to use in the veto list: double ROOT::Minuit2::MnStrategy::HessianG2Tolerance()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnStrategy.h:46:11
    t.method("HessianG2Tolerance", static_cast<double (ROOT::Minuit2::MnStrategy::*)()  const>(&ROOT::Minuit2::MnStrategy::HessianG2Tolerance));

    DEBUG_MSG("Adding wrapper for unsigned int ROOT::Minuit2::MnStrategy::HessianGradientNCycles() (" __HERE__ ")");
    // signature to use in the veto list: unsigned int ROOT::Minuit2::MnStrategy::HessianGradientNCycles()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnStrategy.h:47:17
    t.method("HessianGradientNCycles", static_cast<unsigned int (ROOT::Minuit2::MnStrategy::*)()  const>(&ROOT::Minuit2::MnStrategy::HessianGradientNCycles));

    DEBUG_MSG("Adding wrapper for unsigned int ROOT::Minuit2::MnStrategy::HessianCentralFDMixedDerivatives() (" __HERE__ ")");
    // signature to use in the veto list: unsigned int ROOT::Minuit2::MnStrategy::HessianCentralFDMixedDerivatives()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnStrategy.h:48:17
    t.method("HessianCentralFDMixedDerivatives", static_cast<unsigned int (ROOT::Minuit2::MnStrategy::*)()  const>(&ROOT::Minuit2::MnStrategy::HessianCentralFDMixedDerivatives));

    DEBUG_MSG("Adding wrapper for unsigned int ROOT::Minuit2::MnStrategy::HessianForcePosDef() (" __HERE__ ")");
    // signature to use in the veto list: unsigned int ROOT::Minuit2::MnStrategy::HessianForcePosDef()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnStrategy.h:49:17
    t.method("HessianForcePosDef", static_cast<unsigned int (ROOT::Minuit2::MnStrategy::*)()  const>(&ROOT::Minuit2::MnStrategy::HessianForcePosDef));

    DEBUG_MSG("Adding wrapper for int ROOT::Minuit2::MnStrategy::StorageLevel() (" __HERE__ ")");
    // signature to use in the veto list: int ROOT::Minuit2::MnStrategy::StorageLevel()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnStrategy.h:51:8
    t.method("StorageLevel", static_cast<int (ROOT::Minuit2::MnStrategy::*)()  const>(&ROOT::Minuit2::MnStrategy::StorageLevel));

    DEBUG_MSG("Adding wrapper for bool ROOT::Minuit2::MnStrategy::IsLow() (" __HERE__ ")");
    // signature to use in the veto list: bool ROOT::Minuit2::MnStrategy::IsLow()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnStrategy.h:53:9
    t.method("IsLow", static_cast<bool (ROOT::Minuit2::MnStrategy::*)()  const>(&ROOT::Minuit2::MnStrategy::IsLow));

    DEBUG_MSG("Adding wrapper for bool ROOT::Minuit2::MnStrategy::IsMedium() (" __HERE__ ")");
    // signature to use in the veto list: bool ROOT::Minuit2::MnStrategy::IsMedium()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnStrategy.h:54:9
    t.method("IsMedium", static_cast<bool (ROOT::Minuit2::MnStrategy::*)()  const>(&ROOT::Minuit2::MnStrategy::IsMedium));

    DEBUG_MSG("Adding wrapper for bool ROOT::Minuit2::MnStrategy::IsHigh() (" __HERE__ ")");
    // signature to use in the veto list: bool ROOT::Minuit2::MnStrategy::IsHigh()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnStrategy.h:55:9
    t.method("IsHigh", static_cast<bool (ROOT::Minuit2::MnStrategy::*)()  const>(&ROOT::Minuit2::MnStrategy::IsHigh));

    DEBUG_MSG("Adding wrapper for bool ROOT::Minuit2::MnStrategy::IsVeryHigh() (" __HERE__ ")");
    // signature to use in the veto list: bool ROOT::Minuit2::MnStrategy::IsVeryHigh()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnStrategy.h:56:9
    t.method("IsVeryHigh", static_cast<bool (ROOT::Minuit2::MnStrategy::*)()  const>(&ROOT::Minuit2::MnStrategy::IsVeryHigh));

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnStrategy::SetLowStrategy() (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MnStrategy::SetLowStrategy()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnStrategy.h:58:9
    t.method("SetLowStrategy", static_cast<void (ROOT::Minuit2::MnStrategy::*)() >(&ROOT::Minuit2::MnStrategy::SetLowStrategy));

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnStrategy::SetMediumStrategy() (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MnStrategy::SetMediumStrategy()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnStrategy.h:59:9
    t.method("SetMediumStrategy", static_cast<void (ROOT::Minuit2::MnStrategy::*)() >(&ROOT::Minuit2::MnStrategy::SetMediumStrategy));

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnStrategy::SetHighStrategy() (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MnStrategy::SetHighStrategy()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnStrategy.h:60:9
    t.method("SetHighStrategy", static_cast<void (ROOT::Minuit2::MnStrategy::*)() >(&ROOT::Minuit2::MnStrategy::SetHighStrategy));

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnStrategy::SetVeryHighStrategy() (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MnStrategy::SetVeryHighStrategy()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnStrategy.h:61:9
    t.method("SetVeryHighStrategy", static_cast<void (ROOT::Minuit2::MnStrategy::*)() >(&ROOT::Minuit2::MnStrategy::SetVeryHighStrategy));

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnStrategy::SetGradientNCycles(unsigned int) (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MnStrategy::SetGradientNCycles(unsigned int)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnStrategy.h:63:9
    t.method("SetGradientNCycles", static_cast<void (ROOT::Minuit2::MnStrategy::*)(unsigned int) >(&ROOT::Minuit2::MnStrategy::SetGradientNCycles));

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnStrategy::SetGradientStepTolerance(double) (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MnStrategy::SetGradientStepTolerance(double)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnStrategy.h:64:9
    t.method("SetGradientStepTolerance", static_cast<void (ROOT::Minuit2::MnStrategy::*)(double) >(&ROOT::Minuit2::MnStrategy::SetGradientStepTolerance));

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnStrategy::SetGradientTolerance(double) (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MnStrategy::SetGradientTolerance(double)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnStrategy.h:65:9
    t.method("SetGradientTolerance", static_cast<void (ROOT::Minuit2::MnStrategy::*)(double) >(&ROOT::Minuit2::MnStrategy::SetGradientTolerance));

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnStrategy::SetHessianNCycles(unsigned int) (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MnStrategy::SetHessianNCycles(unsigned int)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnStrategy.h:67:9
    t.method("SetHessianNCycles", static_cast<void (ROOT::Minuit2::MnStrategy::*)(unsigned int) >(&ROOT::Minuit2::MnStrategy::SetHessianNCycles));

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnStrategy::SetHessianStepTolerance(double) (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MnStrategy::SetHessianStepTolerance(double)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnStrategy.h:68:9
    t.method("SetHessianStepTolerance", static_cast<void (ROOT::Minuit2::MnStrategy::*)(double) >(&ROOT::Minuit2::MnStrategy::SetHessianStepTolerance));

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnStrategy::SetHessianG2Tolerance(double) (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MnStrategy::SetHessianG2Tolerance(double)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnStrategy.h:69:9
    t.method("SetHessianG2Tolerance", static_cast<void (ROOT::Minuit2::MnStrategy::*)(double) >(&ROOT::Minuit2::MnStrategy::SetHessianG2Tolerance));

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnStrategy::SetHessianGradientNCycles(unsigned int) (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MnStrategy::SetHessianGradientNCycles(unsigned int)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnStrategy.h:70:9
    t.method("SetHessianGradientNCycles", static_cast<void (ROOT::Minuit2::MnStrategy::*)(unsigned int) >(&ROOT::Minuit2::MnStrategy::SetHessianGradientNCycles));

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnStrategy::SetHessianCentralFDMixedDerivatives(unsigned int) (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MnStrategy::SetHessianCentralFDMixedDerivatives(unsigned int)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnStrategy.h:74:9
    t.method("SetHessianCentralFDMixedDerivatives", static_cast<void (ROOT::Minuit2::MnStrategy::*)(unsigned int) >(&ROOT::Minuit2::MnStrategy::SetHessianCentralFDMixedDerivatives));

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnStrategy::SetHessianForcePosDef(unsigned int) (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MnStrategy::SetHessianForcePosDef(unsigned int)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnStrategy.h:78:9
    t.method("SetHessianForcePosDef", static_cast<void (ROOT::Minuit2::MnStrategy::*)(unsigned int) >(&ROOT::Minuit2::MnStrategy::SetHessianForcePosDef));

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnStrategy::SetStorageLevel(unsigned int) (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MnStrategy::SetStorageLevel(unsigned int)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnStrategy.h:82:9
    t.method("SetStorageLevel", static_cast<void (ROOT::Minuit2::MnStrategy::*)(unsigned int) >(&ROOT::Minuit2::MnStrategy::SetStorageLevel));
  }

private:
  std::unique_ptr<jlcxx::TypeWrapper<ROOT::Minuit2::MnStrategy>> type_;
};
std::shared_ptr<Wrapper> newJlROOT_Minuit2_MnStrategy(jlcxx::Module& module){
  return std::shared_ptr<Wrapper>(new JlROOT_Minuit2_MnStrategy(module));
}
