// this file was auto-generated by wrapit v1.6.0
#include "Wrapper.h"

#include "jlMinuit2.h"
#include "dbg_msg.h"
#include "jlcxx/functions.hpp"
#include "jlcxx/stl.hpp"

namespace jlcxx {
  template<> struct IsMirroredType<ROOT::Minuit2::MnSimplex> : std::false_type { };
  template<> struct DefaultConstructible<ROOT::Minuit2::MnSimplex> : std::false_type { };
template<> struct SuperType<ROOT::Minuit2::MnSimplex> { typedef ROOT::Minuit2::MnApplication type; };
}

// Class generating the wrapper for type ROOT::Minuit2::MnSimplex
// signature to use in the veto file: ROOT::Minuit2::MnSimplex
struct JlROOT_Minuit2_MnSimplex: public Wrapper {

  JlROOT_Minuit2_MnSimplex(jlcxx::Module& jlModule): Wrapper(jlModule){
    DEBUG_MSG("Adding wrapper for type ROOT::Minuit2::MnSimplex (" __HERE__ ")");
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnSimplex.h:35:7
    jlcxx::TypeWrapper<ROOT::Minuit2::MnSimplex>  t = jlModule.add_type<ROOT::Minuit2::MnSimplex>("ROOT!Minuit2!MnSimplex",
      jlcxx::julia_base_type<ROOT::Minuit2::MnApplication>());
    type_ = std::unique_ptr<jlcxx::TypeWrapper<ROOT::Minuit2::MnSimplex>>(new jlcxx::TypeWrapper<ROOT::Minuit2::MnSimplex>(jlModule, t));
  }

  void add_methods() const{
    auto& t = *type_;


    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnSimplex::MnSimplex(const ROOT::Minuit2::FCNBase &, const ROOT::Minuit2::MnUserParameterState &, const ROOT::Minuit2::MnStrategy &) (" __HERE__ ")");
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnSimplex.h:39:4
    t.constructor<const ROOT::Minuit2::FCNBase &, const ROOT::Minuit2::MnUserParameterState &>(/*finalize=*/jlcxx::finalize_policy::yes, jlcxx::arg("this"), jlcxx::arg("fcn"), jlcxx::arg("par")    );
    t.constructor<const ROOT::Minuit2::FCNBase &, const ROOT::Minuit2::MnUserParameterState &, const ROOT::Minuit2::MnStrategy &>(/*finalize=*/jlcxx::finalize_policy::yes, jlcxx::arg("this"), jlcxx::arg("fcn"), jlcxx::arg("par"), jlcxx::arg("str")    );


    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnSimplex::MnSimplex(const ROOT::Minuit2::MnSimplex &) (" __HERE__ ")");
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnSimplex.h:44:4
    t.constructor<const ROOT::Minuit2::MnSimplex &>(/*finalize=*/jlcxx::finalize_policy::yes, jlcxx::arg("this"), jlcxx::arg("migr")    );

    DEBUG_MSG("Adding wrapper for ROOT::Minuit2::ModularFunctionMinimizer & ROOT::Minuit2::MnSimplex::Minimizer() (" __HERE__ ")");
    // signature to use in the veto list: ROOT::Minuit2::ModularFunctionMinimizer & ROOT::Minuit2::MnSimplex::Minimizer()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnSimplex.h:49:30
    t.method("Minimizer", [](ROOT::Minuit2::MnSimplex& a)->ROOT::Minuit2::ModularFunctionMinimizer & { return a.Minimizer(); }, jlcxx::arg("this"));
    t.method("Minimizer", [](ROOT::Minuit2::MnSimplex* a)->ROOT::Minuit2::ModularFunctionMinimizer & { return a->Minimizer(); }, jlcxx::arg("this"));

    DEBUG_MSG("Adding wrapper for const ROOT::Minuit2::ModularFunctionMinimizer & ROOT::Minuit2::MnSimplex::Minimizer() (" __HERE__ ")");
    // signature to use in the veto list: const ROOT::Minuit2::ModularFunctionMinimizer & ROOT::Minuit2::MnSimplex::Minimizer()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnSimplex.h:50:36
    t.method("Minimizer", [](ROOT::Minuit2::MnSimplex const& a)->const ROOT::Minuit2::ModularFunctionMinimizer & { return a.Minimizer(); }, jlcxx::arg("this"));
    t.method("Minimizer", [](ROOT::Minuit2::MnSimplex const* a)->const ROOT::Minuit2::ModularFunctionMinimizer & { return a->Minimizer(); }, jlcxx::arg("this"));
  }

private:
  std::unique_ptr<jlcxx::TypeWrapper<ROOT::Minuit2::MnSimplex>> type_;
};
std::shared_ptr<Wrapper> newJlROOT_Minuit2_MnSimplex(jlcxx::Module& module){
  return std::shared_ptr<Wrapper>(new JlROOT_Minuit2_MnSimplex(module));
}
