// this file was auto-generated by wrapit v1.4.0-3-g14eb9a6
#include "Wrapper.h"

#include "jlMinuit2.h"
#include "dbg_msg.h"
#include "jlcxx/functions.hpp"
#include "jlcxx/stl.hpp"

namespace jlcxx {
  template<> struct IsMirroredType<ROOT::Minuit2::MnUserParameterState> : std::false_type { };
  template<> struct DefaultConstructible<ROOT::Minuit2::MnUserParameterState> : std::false_type { };
}

// Class generating the wrapper for type ROOT::Minuit2::MnUserParameterState
// signature to use in the veto file: ROOT::Minuit2::MnUserParameterState
struct JlROOT_Minuit2_MnUserParameterState: public Wrapper {

  JlROOT_Minuit2_MnUserParameterState(jlcxx::Module& jlModule): Wrapper(jlModule){
    DEBUG_MSG("Adding wrapper for type ROOT::Minuit2::MnUserParameterState (" __HERE__ ")");
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:35:7
    jlcxx::TypeWrapper<ROOT::Minuit2::MnUserParameterState>  t = jlModule.add_type<ROOT::Minuit2::MnUserParameterState>("ROOT!Minuit2!MnUserParameterState");
    type_ = std::unique_ptr<jlcxx::TypeWrapper<ROOT::Minuit2::MnUserParameterState>>(new jlcxx::TypeWrapper<ROOT::Minuit2::MnUserParameterState>(jlModule, t));
  }

  void add_methods() const{
    auto& t = *type_;
    t.template constructor<>(/*finalize=*/jlcxx::finalize_policy::yes);


    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnUserParameterState::MnUserParameterState(const ROOT::Minuit2::MnUserParameters &) (" __HERE__ ")");
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:49:4
    t.constructor<const ROOT::Minuit2::MnUserParameters &>(/*finalize=*/jlcxx::finalize_policy::yes);


    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnUserParameterState::MnUserParameterState(const ROOT::Minuit2::MnUserParameters &, const ROOT::Minuit2::MnUserCovariance &) (" __HERE__ ")");
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:56:4
    t.constructor<const ROOT::Minuit2::MnUserParameters &, const ROOT::Minuit2::MnUserCovariance &>(/*finalize=*/jlcxx::finalize_policy::yes);


    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnUserParameterState::MnUserParameterState(const ROOT::Minuit2::MinimumState &, double, const ROOT::Minuit2::MnUserTransformation &) (" __HERE__ ")");
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:59:4
    t.constructor<const ROOT::Minuit2::MinimumState &, double, const ROOT::Minuit2::MnUserTransformation &>(/*finalize=*/jlcxx::finalize_policy::yes);

    DEBUG_MSG("Adding wrapper for const ROOT::Minuit2::MnUserParameters & ROOT::Minuit2::MnUserParameterState::Parameters() (" __HERE__ ")");
    // signature to use in the veto list: const ROOT::Minuit2::MnUserParameters & ROOT::Minuit2::MnUserParameterState::Parameters()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:62:28
    t.method("Parameters", [](ROOT::Minuit2::MnUserParameterState const& a)->const ROOT::Minuit2::MnUserParameters & { return a.Parameters(); });
    t.method("Parameters", [](ROOT::Minuit2::MnUserParameterState const* a)->const ROOT::Minuit2::MnUserParameters & { return a->Parameters(); });

    DEBUG_MSG("Adding wrapper for const ROOT::Minuit2::MnUserCovariance & ROOT::Minuit2::MnUserParameterState::Covariance() (" __HERE__ ")");
    // signature to use in the veto list: const ROOT::Minuit2::MnUserCovariance & ROOT::Minuit2::MnUserParameterState::Covariance()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:63:28
    t.method("Covariance", [](ROOT::Minuit2::MnUserParameterState const& a)->const ROOT::Minuit2::MnUserCovariance & { return a.Covariance(); });
    t.method("Covariance", [](ROOT::Minuit2::MnUserParameterState const* a)->const ROOT::Minuit2::MnUserCovariance & { return a->Covariance(); });

    DEBUG_MSG("Adding wrapper for const ROOT::Minuit2::MnGlobalCorrelationCoeff & ROOT::Minuit2::MnUserParameterState::GlobalCC() (" __HERE__ ")");
    // signature to use in the veto list: const ROOT::Minuit2::MnGlobalCorrelationCoeff & ROOT::Minuit2::MnUserParameterState::GlobalCC()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:64:36
    t.method("GlobalCC", [](ROOT::Minuit2::MnUserParameterState const& a)->const ROOT::Minuit2::MnGlobalCorrelationCoeff & { return a.GlobalCC(); });
    t.method("GlobalCC", [](ROOT::Minuit2::MnUserParameterState const* a)->const ROOT::Minuit2::MnGlobalCorrelationCoeff & { return a->GlobalCC(); });

    DEBUG_MSG("Adding wrapper for ROOT::Minuit2::MnUserCovariance ROOT::Minuit2::MnUserParameterState::Hessian() (" __HERE__ ")");
    // signature to use in the veto list: ROOT::Minuit2::MnUserCovariance ROOT::Minuit2::MnUserParameterState::Hessian()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:67:21
    t.method("Hessian", [](ROOT::Minuit2::MnUserParameterState const& a)->ROOT::Minuit2::MnUserCovariance { return a.Hessian(); });
    t.method("Hessian", [](ROOT::Minuit2::MnUserParameterState const* a)->ROOT::Minuit2::MnUserCovariance { return a->Hessian(); });

    DEBUG_MSG("Adding wrapper for const std::vector<double> & ROOT::Minuit2::MnUserParameterState::IntParameters() (" __HERE__ ")");
    // signature to use in the veto list: const std::vector<double> & ROOT::Minuit2::MnUserParameterState::IntParameters()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:70:31
    t.method("IntParameters", [](ROOT::Minuit2::MnUserParameterState const& a)->const std::vector<double> & { return a.IntParameters(); });
    t.method("IntParameters", [](ROOT::Minuit2::MnUserParameterState const* a)->const std::vector<double> & { return a->IntParameters(); });

    DEBUG_MSG("Adding wrapper for const ROOT::Minuit2::MnUserCovariance & ROOT::Minuit2::MnUserParameterState::IntCovariance() (" __HERE__ ")");
    // signature to use in the veto list: const ROOT::Minuit2::MnUserCovariance & ROOT::Minuit2::MnUserParameterState::IntCovariance()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:71:28
    t.method("IntCovariance", [](ROOT::Minuit2::MnUserParameterState const& a)->const ROOT::Minuit2::MnUserCovariance & { return a.IntCovariance(); });
    t.method("IntCovariance", [](ROOT::Minuit2::MnUserParameterState const* a)->const ROOT::Minuit2::MnUserCovariance & { return a->IntCovariance(); });

    DEBUG_MSG("Adding wrapper for int ROOT::Minuit2::MnUserParameterState::CovarianceStatus() (" __HERE__ ")");
    // signature to use in the veto list: int ROOT::Minuit2::MnUserParameterState::CovarianceStatus()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:74:8
    t.method("CovarianceStatus", [](ROOT::Minuit2::MnUserParameterState const& a)->int { return a.CovarianceStatus(); });
    t.method("CovarianceStatus", [](ROOT::Minuit2::MnUserParameterState const* a)->int { return a->CovarianceStatus(); });

    DEBUG_MSG("Adding wrapper for const ROOT::Minuit2::MnUserTransformation & ROOT::Minuit2::MnUserParameterState::Trafo() (" __HERE__ ")");
    // signature to use in the veto list: const ROOT::Minuit2::MnUserTransformation & ROOT::Minuit2::MnUserParameterState::Trafo()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:77:32
    t.method("Trafo", [](ROOT::Minuit2::MnUserParameterState const& a)->const ROOT::Minuit2::MnUserTransformation & { return a.Trafo(); });
    t.method("Trafo", [](ROOT::Minuit2::MnUserParameterState const* a)->const ROOT::Minuit2::MnUserTransformation & { return a->Trafo(); });

    DEBUG_MSG("Adding wrapper for bool ROOT::Minuit2::MnUserParameterState::IsValid() (" __HERE__ ")");
    // signature to use in the veto list: bool ROOT::Minuit2::MnUserParameterState::IsValid()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:79:9
    t.method("IsValid", [](ROOT::Minuit2::MnUserParameterState const& a)->bool { return a.IsValid(); });
    t.method("IsValid", [](ROOT::Minuit2::MnUserParameterState const* a)->bool { return a->IsValid(); });

    DEBUG_MSG("Adding wrapper for bool ROOT::Minuit2::MnUserParameterState::HasCovariance() (" __HERE__ ")");
    // signature to use in the veto list: bool ROOT::Minuit2::MnUserParameterState::HasCovariance()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:80:9
    t.method("HasCovariance", [](ROOT::Minuit2::MnUserParameterState const& a)->bool { return a.HasCovariance(); });
    t.method("HasCovariance", [](ROOT::Minuit2::MnUserParameterState const* a)->bool { return a->HasCovariance(); });

    DEBUG_MSG("Adding wrapper for bool ROOT::Minuit2::MnUserParameterState::HasGlobalCC() (" __HERE__ ")");
    // signature to use in the veto list: bool ROOT::Minuit2::MnUserParameterState::HasGlobalCC()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:81:9
    t.method("HasGlobalCC", [](ROOT::Minuit2::MnUserParameterState const& a)->bool { return a.HasGlobalCC(); });
    t.method("HasGlobalCC", [](ROOT::Minuit2::MnUserParameterState const* a)->bool { return a->HasGlobalCC(); });

    DEBUG_MSG("Adding wrapper for double ROOT::Minuit2::MnUserParameterState::Fval() (" __HERE__ ")");
    // signature to use in the veto list: double ROOT::Minuit2::MnUserParameterState::Fval()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:83:11
    t.method("Fval", [](ROOT::Minuit2::MnUserParameterState const& a)->double { return a.Fval(); });
    t.method("Fval", [](ROOT::Minuit2::MnUserParameterState const* a)->double { return a->Fval(); });

    DEBUG_MSG("Adding wrapper for double ROOT::Minuit2::MnUserParameterState::Edm() (" __HERE__ ")");
    // signature to use in the veto list: double ROOT::Minuit2::MnUserParameterState::Edm()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:84:11
    t.method("Edm", [](ROOT::Minuit2::MnUserParameterState const& a)->double { return a.Edm(); });
    t.method("Edm", [](ROOT::Minuit2::MnUserParameterState const* a)->double { return a->Edm(); });

    DEBUG_MSG("Adding wrapper for unsigned int ROOT::Minuit2::MnUserParameterState::NFcn() (" __HERE__ ")");
    // signature to use in the veto list: unsigned int ROOT::Minuit2::MnUserParameterState::NFcn()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:85:17
    t.method("NFcn", [](ROOT::Minuit2::MnUserParameterState const& a)->unsigned int { return a.NFcn(); });
    t.method("NFcn", [](ROOT::Minuit2::MnUserParameterState const* a)->unsigned int { return a->NFcn(); });

    DEBUG_MSG("Adding wrapper for const std::vector<ROOT::Minuit2::MinuitParameter> & ROOT::Minuit2::MnUserParameterState::MinuitParameters() (" __HERE__ ")");
    // signature to use in the veto list: const std::vector<ROOT::Minuit2::MinuitParameter> & ROOT::Minuit2::MnUserParameterState::MinuitParameters()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:91:55
    t.method("MinuitParameters", [](ROOT::Minuit2::MnUserParameterState const& a)->const std::vector<ROOT::Minuit2::MinuitParameter> & { return a.MinuitParameters(); });
    t.method("MinuitParameters", [](ROOT::Minuit2::MnUserParameterState const* a)->const std::vector<ROOT::Minuit2::MinuitParameter> & { return a->MinuitParameters(); });

    DEBUG_MSG("Adding wrapper for std::vector<double> ROOT::Minuit2::MnUserParameterState::Params() (" __HERE__ ")");
    // signature to use in the veto list: std::vector<double> ROOT::Minuit2::MnUserParameterState::Params()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:93:24
    t.method("Params", [](ROOT::Minuit2::MnUserParameterState const& a)->std::vector<double> { return a.Params(); });
    t.method("Params", [](ROOT::Minuit2::MnUserParameterState const* a)->std::vector<double> { return a->Params(); });

    DEBUG_MSG("Adding wrapper for std::vector<double> ROOT::Minuit2::MnUserParameterState::Errors() (" __HERE__ ")");
    // signature to use in the veto list: std::vector<double> ROOT::Minuit2::MnUserParameterState::Errors()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:94:24
    t.method("Errors", [](ROOT::Minuit2::MnUserParameterState const& a)->std::vector<double> { return a.Errors(); });
    t.method("Errors", [](ROOT::Minuit2::MnUserParameterState const* a)->std::vector<double> { return a->Errors(); });

    DEBUG_MSG("Adding wrapper for const ROOT::Minuit2::MinuitParameter & ROOT::Minuit2::MnUserParameterState::Parameter(unsigned int) (" __HERE__ ")");
    // signature to use in the veto list: const ROOT::Minuit2::MinuitParameter & ROOT::Minuit2::MnUserParameterState::Parameter(unsigned int)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:97:27
    t.method("Parameter", [](ROOT::Minuit2::MnUserParameterState const& a, unsigned int arg0)->const ROOT::Minuit2::MinuitParameter & { return a.Parameter(arg0); });
    t.method("Parameter", [](ROOT::Minuit2::MnUserParameterState const* a, unsigned int arg0)->const ROOT::Minuit2::MinuitParameter & { return a->Parameter(arg0); });

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnUserParameterState::Add(const std::string &, double, double) (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MnUserParameterState::Add(const std::string &, double, double)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:100:9
    t.method("Add", [](ROOT::Minuit2::MnUserParameterState& a, const std::string & arg0, double arg1, double arg2)->void { a.Add(arg0, arg1, arg2); });
    t.method("Add", [](ROOT::Minuit2::MnUserParameterState* a, const std::string & arg0, double arg1, double arg2)->void { a->Add(arg0, arg1, arg2); });

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnUserParameterState::Add(const std::string &, double, double, double, double) (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MnUserParameterState::Add(const std::string &, double, double, double, double)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:102:9
    t.method("Add", [](ROOT::Minuit2::MnUserParameterState& a, const std::string & arg0, double arg1, double arg2, double arg3, double arg4)->void { a.Add(arg0, arg1, arg2, arg3, arg4); });
    t.method("Add", [](ROOT::Minuit2::MnUserParameterState* a, const std::string & arg0, double arg1, double arg2, double arg3, double arg4)->void { a->Add(arg0, arg1, arg2, arg3, arg4); });

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnUserParameterState::Add(const std::string &, double) (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MnUserParameterState::Add(const std::string &, double)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:104:9
    t.method("Add", [](ROOT::Minuit2::MnUserParameterState& a, const std::string & arg0, double arg1)->void { a.Add(arg0, arg1); });
    t.method("Add", [](ROOT::Minuit2::MnUserParameterState* a, const std::string & arg0, double arg1)->void { a->Add(arg0, arg1); });

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnUserParameterState::AddCovariance(const ROOT::Minuit2::MnUserCovariance &) (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MnUserParameterState::AddCovariance(const ROOT::Minuit2::MnUserCovariance &)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:107:9
    t.method("AddCovariance", [](ROOT::Minuit2::MnUserParameterState& a, const ROOT::Minuit2::MnUserCovariance & arg0)->void { a.AddCovariance(arg0); });
    t.method("AddCovariance", [](ROOT::Minuit2::MnUserParameterState* a, const ROOT::Minuit2::MnUserCovariance & arg0)->void { a->AddCovariance(arg0); });

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnUserParameterState::Fix(unsigned int) (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MnUserParameterState::Fix(unsigned int)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:110:9
    t.method("Fix", [](ROOT::Minuit2::MnUserParameterState& a, unsigned int arg0)->void { a.Fix(arg0); });
    t.method("Fix", [](ROOT::Minuit2::MnUserParameterState* a, unsigned int arg0)->void { a->Fix(arg0); });

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnUserParameterState::Release(unsigned int) (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MnUserParameterState::Release(unsigned int)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:111:9
    t.method("Release", [](ROOT::Minuit2::MnUserParameterState& a, unsigned int arg0)->void { a.Release(arg0); });
    t.method("Release", [](ROOT::Minuit2::MnUserParameterState* a, unsigned int arg0)->void { a->Release(arg0); });

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnUserParameterState::RemoveLimits(unsigned int) (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MnUserParameterState::RemoveLimits(unsigned int)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:112:9
    t.method("RemoveLimits", [](ROOT::Minuit2::MnUserParameterState& a, unsigned int arg0)->void { a.RemoveLimits(arg0); });
    t.method("RemoveLimits", [](ROOT::Minuit2::MnUserParameterState* a, unsigned int arg0)->void { a->RemoveLimits(arg0); });

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnUserParameterState::SetValue(unsigned int, double) (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MnUserParameterState::SetValue(unsigned int, double)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:113:9
    t.method("SetValue", [](ROOT::Minuit2::MnUserParameterState& a, unsigned int arg0, double arg1)->void { a.SetValue(arg0, arg1); });
    t.method("SetValue", [](ROOT::Minuit2::MnUserParameterState* a, unsigned int arg0, double arg1)->void { a->SetValue(arg0, arg1); });

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnUserParameterState::SetError(unsigned int, double) (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MnUserParameterState::SetError(unsigned int, double)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:114:9
    t.method("SetError", [](ROOT::Minuit2::MnUserParameterState& a, unsigned int arg0, double arg1)->void { a.SetError(arg0, arg1); });
    t.method("SetError", [](ROOT::Minuit2::MnUserParameterState* a, unsigned int arg0, double arg1)->void { a->SetError(arg0, arg1); });

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnUserParameterState::SetLimits(unsigned int, double, double) (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MnUserParameterState::SetLimits(unsigned int, double, double)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:115:9
    t.method("SetLimits", [](ROOT::Minuit2::MnUserParameterState& a, unsigned int arg0, double arg1, double arg2)->void { a.SetLimits(arg0, arg1, arg2); });
    t.method("SetLimits", [](ROOT::Minuit2::MnUserParameterState* a, unsigned int arg0, double arg1, double arg2)->void { a->SetLimits(arg0, arg1, arg2); });

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnUserParameterState::SetUpperLimit(unsigned int, double) (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MnUserParameterState::SetUpperLimit(unsigned int, double)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:116:9
    t.method("SetUpperLimit", [](ROOT::Minuit2::MnUserParameterState& a, unsigned int arg0, double arg1)->void { a.SetUpperLimit(arg0, arg1); });
    t.method("SetUpperLimit", [](ROOT::Minuit2::MnUserParameterState* a, unsigned int arg0, double arg1)->void { a->SetUpperLimit(arg0, arg1); });

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnUserParameterState::SetLowerLimit(unsigned int, double) (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MnUserParameterState::SetLowerLimit(unsigned int, double)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:117:9
    t.method("SetLowerLimit", [](ROOT::Minuit2::MnUserParameterState& a, unsigned int arg0, double arg1)->void { a.SetLowerLimit(arg0, arg1); });
    t.method("SetLowerLimit", [](ROOT::Minuit2::MnUserParameterState* a, unsigned int arg0, double arg1)->void { a->SetLowerLimit(arg0, arg1); });

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnUserParameterState::SetName(unsigned int, const std::string &) (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MnUserParameterState::SetName(unsigned int, const std::string &)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:118:9
    t.method("SetName", [](ROOT::Minuit2::MnUserParameterState& a, unsigned int arg0, const std::string & arg1)->void { a.SetName(arg0, arg1); });
    t.method("SetName", [](ROOT::Minuit2::MnUserParameterState* a, unsigned int arg0, const std::string & arg1)->void { a->SetName(arg0, arg1); });

    DEBUG_MSG("Adding wrapper for double ROOT::Minuit2::MnUserParameterState::Value(unsigned int) (" __HERE__ ")");
    // signature to use in the veto list: double ROOT::Minuit2::MnUserParameterState::Value(unsigned int)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:120:11
    t.method("Value", [](ROOT::Minuit2::MnUserParameterState const& a, unsigned int arg0)->double { return a.Value(arg0); });
    t.method("Value", [](ROOT::Minuit2::MnUserParameterState const* a, unsigned int arg0)->double { return a->Value(arg0); });

    DEBUG_MSG("Adding wrapper for double ROOT::Minuit2::MnUserParameterState::Error(unsigned int) (" __HERE__ ")");
    // signature to use in the veto list: double ROOT::Minuit2::MnUserParameterState::Error(unsigned int)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:121:11
    t.method("Error", [](ROOT::Minuit2::MnUserParameterState const& a, unsigned int arg0)->double { return a.Error(arg0); });
    t.method("Error", [](ROOT::Minuit2::MnUserParameterState const* a, unsigned int arg0)->double { return a->Error(arg0); });

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnUserParameterState::Fix(const std::string &) (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MnUserParameterState::Fix(const std::string &)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:124:9
    t.method("Fix", [](ROOT::Minuit2::MnUserParameterState& a, const std::string & arg0)->void { a.Fix(arg0); });
    t.method("Fix", [](ROOT::Minuit2::MnUserParameterState* a, const std::string & arg0)->void { a->Fix(arg0); });

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnUserParameterState::Release(const std::string &) (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MnUserParameterState::Release(const std::string &)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:125:9
    t.method("Release", [](ROOT::Minuit2::MnUserParameterState& a, const std::string & arg0)->void { a.Release(arg0); });
    t.method("Release", [](ROOT::Minuit2::MnUserParameterState* a, const std::string & arg0)->void { a->Release(arg0); });

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnUserParameterState::SetValue(const std::string &, double) (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MnUserParameterState::SetValue(const std::string &, double)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:126:9
    t.method("SetValue", [](ROOT::Minuit2::MnUserParameterState& a, const std::string & arg0, double arg1)->void { a.SetValue(arg0, arg1); });
    t.method("SetValue", [](ROOT::Minuit2::MnUserParameterState* a, const std::string & arg0, double arg1)->void { a->SetValue(arg0, arg1); });

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnUserParameterState::SetError(const std::string &, double) (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MnUserParameterState::SetError(const std::string &, double)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:127:9
    t.method("SetError", [](ROOT::Minuit2::MnUserParameterState& a, const std::string & arg0, double arg1)->void { a.SetError(arg0, arg1); });
    t.method("SetError", [](ROOT::Minuit2::MnUserParameterState* a, const std::string & arg0, double arg1)->void { a->SetError(arg0, arg1); });

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnUserParameterState::SetLimits(const std::string &, double, double) (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MnUserParameterState::SetLimits(const std::string &, double, double)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:128:9
    t.method("SetLimits", [](ROOT::Minuit2::MnUserParameterState& a, const std::string & arg0, double arg1, double arg2)->void { a.SetLimits(arg0, arg1, arg2); });
    t.method("SetLimits", [](ROOT::Minuit2::MnUserParameterState* a, const std::string & arg0, double arg1, double arg2)->void { a->SetLimits(arg0, arg1, arg2); });

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnUserParameterState::SetUpperLimit(const std::string &, double) (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MnUserParameterState::SetUpperLimit(const std::string &, double)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:129:9
    t.method("SetUpperLimit", [](ROOT::Minuit2::MnUserParameterState& a, const std::string & arg0, double arg1)->void { a.SetUpperLimit(arg0, arg1); });
    t.method("SetUpperLimit", [](ROOT::Minuit2::MnUserParameterState* a, const std::string & arg0, double arg1)->void { a->SetUpperLimit(arg0, arg1); });

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnUserParameterState::SetLowerLimit(const std::string &, double) (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MnUserParameterState::SetLowerLimit(const std::string &, double)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:130:9
    t.method("SetLowerLimit", [](ROOT::Minuit2::MnUserParameterState& a, const std::string & arg0, double arg1)->void { a.SetLowerLimit(arg0, arg1); });
    t.method("SetLowerLimit", [](ROOT::Minuit2::MnUserParameterState* a, const std::string & arg0, double arg1)->void { a->SetLowerLimit(arg0, arg1); });

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnUserParameterState::RemoveLimits(const std::string &) (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MnUserParameterState::RemoveLimits(const std::string &)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:131:9
    t.method("RemoveLimits", [](ROOT::Minuit2::MnUserParameterState& a, const std::string & arg0)->void { a.RemoveLimits(arg0); });
    t.method("RemoveLimits", [](ROOT::Minuit2::MnUserParameterState* a, const std::string & arg0)->void { a->RemoveLimits(arg0); });

    DEBUG_MSG("Adding wrapper for double ROOT::Minuit2::MnUserParameterState::Value(const std::string &) (" __HERE__ ")");
    // signature to use in the veto list: double ROOT::Minuit2::MnUserParameterState::Value(const std::string &)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:133:11
    t.method("Value", [](ROOT::Minuit2::MnUserParameterState const& a, const std::string & arg0)->double { return a.Value(arg0); });
    t.method("Value", [](ROOT::Minuit2::MnUserParameterState const* a, const std::string & arg0)->double { return a->Value(arg0); });

    DEBUG_MSG("Adding wrapper for double ROOT::Minuit2::MnUserParameterState::Error(const std::string &) (" __HERE__ ")");
    // signature to use in the veto list: double ROOT::Minuit2::MnUserParameterState::Error(const std::string &)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:134:11
    t.method("Error", [](ROOT::Minuit2::MnUserParameterState const& a, const std::string & arg0)->double { return a.Error(arg0); });
    t.method("Error", [](ROOT::Minuit2::MnUserParameterState const* a, const std::string & arg0)->double { return a->Error(arg0); });

    DEBUG_MSG("Adding wrapper for unsigned int ROOT::Minuit2::MnUserParameterState::Index(const std::string &) (" __HERE__ ")");
    // signature to use in the veto list: unsigned int ROOT::Minuit2::MnUserParameterState::Index(const std::string &)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:137:17
    t.method("Index", [](ROOT::Minuit2::MnUserParameterState const& a, const std::string & arg0)->unsigned int { return a.Index(arg0); });
    t.method("Index", [](ROOT::Minuit2::MnUserParameterState const* a, const std::string & arg0)->unsigned int { return a->Index(arg0); });

    DEBUG_MSG("Adding wrapper for const std::string & ROOT::Minuit2::MnUserParameterState::GetName(unsigned int) (" __HERE__ ")");
    // signature to use in the veto list: const std::string & ROOT::Minuit2::MnUserParameterState::GetName(unsigned int)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:139:23
    t.method("GetName", [](ROOT::Minuit2::MnUserParameterState const& a, unsigned int arg0)->const std::string & { return a.GetName(arg0); });
    t.method("GetName", [](ROOT::Minuit2::MnUserParameterState const* a, unsigned int arg0)->const std::string & { return a->GetName(arg0); });

    DEBUG_MSG("Adding wrapper for const char * ROOT::Minuit2::MnUserParameterState::Name(unsigned int) (" __HERE__ ")");
    // signature to use in the veto list: const char * ROOT::Minuit2::MnUserParameterState::Name(unsigned int)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:141:16
    t.method("Name", [](ROOT::Minuit2::MnUserParameterState const& a, unsigned int arg0) { return (std::string)a.Name(arg0); });
    t.method("Name", [](ROOT::Minuit2::MnUserParameterState const* a, unsigned int arg0) { return (std::string)a->Name(arg0); });

    DEBUG_MSG("Adding wrapper for double ROOT::Minuit2::MnUserParameterState::Int2ext(unsigned int, double) (" __HERE__ ")");
    // signature to use in the veto list: double ROOT::Minuit2::MnUserParameterState::Int2ext(unsigned int, double)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:144:11
    t.method("Int2ext", [](ROOT::Minuit2::MnUserParameterState const& a, unsigned int arg0, double arg1)->double { return a.Int2ext(arg0, arg1); });
    t.method("Int2ext", [](ROOT::Minuit2::MnUserParameterState const* a, unsigned int arg0, double arg1)->double { return a->Int2ext(arg0, arg1); });

    DEBUG_MSG("Adding wrapper for double ROOT::Minuit2::MnUserParameterState::Ext2int(unsigned int, double) (" __HERE__ ")");
    // signature to use in the veto list: double ROOT::Minuit2::MnUserParameterState::Ext2int(unsigned int, double)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:145:11
    t.method("Ext2int", [](ROOT::Minuit2::MnUserParameterState const& a, unsigned int arg0, double arg1)->double { return a.Ext2int(arg0, arg1); });
    t.method("Ext2int", [](ROOT::Minuit2::MnUserParameterState const* a, unsigned int arg0, double arg1)->double { return a->Ext2int(arg0, arg1); });

    DEBUG_MSG("Adding wrapper for unsigned int ROOT::Minuit2::MnUserParameterState::IntOfExt(unsigned int) (" __HERE__ ")");
    // signature to use in the veto list: unsigned int ROOT::Minuit2::MnUserParameterState::IntOfExt(unsigned int)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:146:17
    t.method("IntOfExt", [](ROOT::Minuit2::MnUserParameterState const& a, unsigned int arg0)->unsigned int { return a.IntOfExt(arg0); });
    t.method("IntOfExt", [](ROOT::Minuit2::MnUserParameterState const* a, unsigned int arg0)->unsigned int { return a->IntOfExt(arg0); });

    DEBUG_MSG("Adding wrapper for unsigned int ROOT::Minuit2::MnUserParameterState::ExtOfInt(unsigned int) (" __HERE__ ")");
    // signature to use in the veto list: unsigned int ROOT::Minuit2::MnUserParameterState::ExtOfInt(unsigned int)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:147:17
    t.method("ExtOfInt", [](ROOT::Minuit2::MnUserParameterState const& a, unsigned int arg0)->unsigned int { return a.ExtOfInt(arg0); });
    t.method("ExtOfInt", [](ROOT::Minuit2::MnUserParameterState const* a, unsigned int arg0)->unsigned int { return a->ExtOfInt(arg0); });

    DEBUG_MSG("Adding wrapper for unsigned int ROOT::Minuit2::MnUserParameterState::VariableParameters() (" __HERE__ ")");
    // signature to use in the veto list: unsigned int ROOT::Minuit2::MnUserParameterState::VariableParameters()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:148:17
    t.method("VariableParameters", [](ROOT::Minuit2::MnUserParameterState const& a)->unsigned int { return a.VariableParameters(); });
    t.method("VariableParameters", [](ROOT::Minuit2::MnUserParameterState const* a)->unsigned int { return a->VariableParameters(); });

    DEBUG_MSG("Adding wrapper for const ROOT::Minuit2::MnMachinePrecision & ROOT::Minuit2::MnUserParameterState::Precision() (" __HERE__ ")");
    // signature to use in the veto list: const ROOT::Minuit2::MnMachinePrecision & ROOT::Minuit2::MnUserParameterState::Precision()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:149:30
    t.method("Precision", [](ROOT::Minuit2::MnUserParameterState const& a)->const ROOT::Minuit2::MnMachinePrecision & { return a.Precision(); });
    t.method("Precision", [](ROOT::Minuit2::MnUserParameterState const* a)->const ROOT::Minuit2::MnMachinePrecision & { return a->Precision(); });

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnUserParameterState::SetPrecision(double) (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MnUserParameterState::SetPrecision(double)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:150:9
    t.method("SetPrecision", [](ROOT::Minuit2::MnUserParameterState& a, double arg0)->void { a.SetPrecision(arg0); });
    t.method("SetPrecision", [](ROOT::Minuit2::MnUserParameterState* a, double arg0)->void { a->SetPrecision(arg0); });
  }

private:
  std::unique_ptr<jlcxx::TypeWrapper<ROOT::Minuit2::MnUserParameterState>> type_;
};
std::shared_ptr<Wrapper> newJlROOT_Minuit2_MnUserParameterState(jlcxx::Module& module){
  return std::shared_ptr<Wrapper>(new JlROOT_Minuit2_MnUserParameterState(module));
}
