// this file was auto-generated by wrapit 5168a24-dirty
#include "Wrapper.h"

#include "jlMinuit2.h"
#include "dbg_msg.h"
#include "jlcxx/functions.hpp"
#include "jlcxx/stl.hpp"

namespace jlcxx {
  template<> struct IsMirroredType<ROOT::Minuit2::LAVector> : std::false_type { };
  template<> struct DefaultConstructible<ROOT::Minuit2::LAVector> : std::false_type { };
}

// Class generating the wrapper for type ROOT::Minuit2::LAVector
// signature to use in the veto file: ROOT::Minuit2::LAVector
struct JlROOT_Minuit2_LAVector: public Wrapper {

  JlROOT_Minuit2_LAVector(jlcxx::Module& jlModule): Wrapper(jlModule){
    DEBUG_MSG("Adding wrapper for type ROOT::Minuit2::LAVector (" __HERE__ ")");
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/LAVector.h:32:7
    jlcxx::TypeWrapper<ROOT::Minuit2::LAVector>  t = jlModule.add_type<ROOT::Minuit2::LAVector>("ROOT!Minuit2!LAVector");
    type_ = std::unique_ptr<jlcxx::TypeWrapper<ROOT::Minuit2::LAVector>>(new jlcxx::TypeWrapper<ROOT::Minuit2::LAVector>(jlModule, t));
  }

  void add_methods() const{
    auto& t = *type_;


    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::LAVector::LAVector(unsigned int) (" __HERE__ ")");
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/LAVector.h:40:4
    t.constructor<unsigned int>(/*finalize=*/jlcxx::finalize_policy::yes);


    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::LAVector::LAVector(const ROOT::Minuit2::LAVector &) (" __HERE__ ")");
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/LAVector.h:61:4
    t.constructor<const ROOT::Minuit2::LAVector &>(/*finalize=*/jlcxx::finalize_policy::yes);

    DEBUG_MSG("Adding wrapper for ROOT::Minuit2::LAVector & ROOT::Minuit2::LAVector::operator=(const ROOT::Minuit2::LAVector &) (" __HERE__ ")");
    // signature to use in the veto list: ROOT::Minuit2::LAVector & ROOT::Minuit2::LAVector::operator=(const ROOT::Minuit2::LAVector &)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/LAVector.h:68:14
    t.method("assign", static_cast<ROOT::Minuit2::LAVector & (ROOT::Minuit2::LAVector::*)(const ROOT::Minuit2::LAVector &) >(&ROOT::Minuit2::LAVector::operator=));

    DEBUG_MSG("Adding wrapper for ROOT::Minuit2::LAVector & ROOT::Minuit2::LAVector::operator+=(const ROOT::Minuit2::LAVector &) (" __HERE__ ")");
    // signature to use in the veto list: ROOT::Minuit2::LAVector & ROOT::Minuit2::LAVector::operator+=(const ROOT::Minuit2::LAVector &)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/LAVector.h:151:14
    t.method("add!", static_cast<ROOT::Minuit2::LAVector & (ROOT::Minuit2::LAVector::*)(const ROOT::Minuit2::LAVector &) >(&ROOT::Minuit2::LAVector::operator+=));

    DEBUG_MSG("Adding wrapper for ROOT::Minuit2::LAVector & ROOT::Minuit2::LAVector::operator-=(const ROOT::Minuit2::LAVector &) (" __HERE__ ")");
    // signature to use in the veto list: ROOT::Minuit2::LAVector & ROOT::Minuit2::LAVector::operator-=(const ROOT::Minuit2::LAVector &)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/LAVector.h:159:14
    t.method("sub!", static_cast<ROOT::Minuit2::LAVector & (ROOT::Minuit2::LAVector::*)(const ROOT::Minuit2::LAVector &) >(&ROOT::Minuit2::LAVector::operator-=));

    DEBUG_MSG("Adding wrapper for ROOT::Minuit2::LAVector & ROOT::Minuit2::LAVector::operator*=(double) (" __HERE__ ")");
    // signature to use in the veto list: ROOT::Minuit2::LAVector & ROOT::Minuit2::LAVector::operator*=(double)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/LAVector.h:197:14
    t.method("mult!", static_cast<ROOT::Minuit2::LAVector & (ROOT::Minuit2::LAVector::*)(double) >(&ROOT::Minuit2::LAVector::operator*=));

    DEBUG_MSG("Adding wrapper for double ROOT::Minuit2::LAVector::operator()(unsigned int) (" __HERE__ ")");
    // signature to use in the veto list: double ROOT::Minuit2::LAVector::operator()(unsigned int)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/LAVector.h:203:11
    t.method("paren", static_cast<double (ROOT::Minuit2::LAVector::*)(unsigned int)  const>(&ROOT::Minuit2::LAVector::operator()));

    DEBUG_MSG("Adding wrapper for double & ROOT::Minuit2::LAVector::operator()(unsigned int) (" __HERE__ ")");
    // signature to use in the veto list: double & ROOT::Minuit2::LAVector::operator()(unsigned int)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/LAVector.h:209:12
    t.method("paren", static_cast<double & (ROOT::Minuit2::LAVector::*)(unsigned int) >(&ROOT::Minuit2::LAVector::operator()));
    module_.set_override_module(jl_base_module);


    DEBUG_MSG("Adding getindex method to wrap double ROOT::Minuit2::LAVector::operator[](unsigned int) (" __HERE__ ")");
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/LAVector.h:215:11
    t.method("getindex",
      [](ROOT::Minuit2::LAVector& a, unsigned int i){
      return a[i];
    });


    DEBUG_MSG("Adding setindex! method  to wrap double & ROOT::Minuit2::LAVector::operator[](unsigned int) (" __HERE__ ")");
// defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/LAVector.h:221:12
    t.method("setindex!",
      [](ROOT::Minuit2::LAVector& a, unsigned int i, double const & val){
      return a[i] = val;
    });

    module_.unset_override_module();

    DEBUG_MSG("Adding wrapper for const double * ROOT::Minuit2::LAVector::Data() (" __HERE__ ")");
    // signature to use in the veto list: const double * ROOT::Minuit2::LAVector::Data()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/LAVector.h:227:18
    t.method("Data", static_cast<const double * (ROOT::Minuit2::LAVector::*)()  const>(&ROOT::Minuit2::LAVector::Data));

    DEBUG_MSG("Adding wrapper for double * ROOT::Minuit2::LAVector::Data() (" __HERE__ ")");
    // signature to use in the veto list: double * ROOT::Minuit2::LAVector::Data()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/LAVector.h:229:12
    t.method("Data", static_cast<double * (ROOT::Minuit2::LAVector::*)() >(&ROOT::Minuit2::LAVector::Data));

    DEBUG_MSG("Adding wrapper for unsigned int ROOT::Minuit2::LAVector::size() (" __HERE__ ")");
    // signature to use in the veto list: unsigned int ROOT::Minuit2::LAVector::size()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/LAVector.h:231:17
    t.method("size", static_cast<unsigned int (ROOT::Minuit2::LAVector::*)()  const>(&ROOT::Minuit2::LAVector::size));
  }

private:
  std::unique_ptr<jlcxx::TypeWrapper<ROOT::Minuit2::LAVector>> type_;
};
std::shared_ptr<Wrapper> newJlROOT_Minuit2_LAVector(jlcxx::Module& module){
  return std::shared_ptr<Wrapper>(new JlROOT_Minuit2_LAVector(module));
}
