// this file was auto-generated by wrapit 5168a24-dirty
#include "Wrapper.h"

#include "jlMinuit2.h"
#include "dbg_msg.h"
#include "jlcxx/functions.hpp"
#include "jlcxx/stl.hpp"

namespace jlcxx {
  template<> struct IsMirroredType<ROOT::Minuit2::MnUserParameterState> : std::false_type { };
  template<> struct DefaultConstructible<ROOT::Minuit2::MnUserParameterState> : std::false_type { };
}

// Class generating the wrapper for type ROOT::Minuit2::MnUserParameterState
// signature to use in the veto file: ROOT::Minuit2::MnUserParameterState
struct JlROOT_Minuit2_MnUserParameterState: public Wrapper {

  JlROOT_Minuit2_MnUserParameterState(jlcxx::Module& jlModule): Wrapper(jlModule){
    DEBUG_MSG("Adding wrapper for type ROOT::Minuit2::MnUserParameterState (" __HERE__ ")");
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:35:7
    jlcxx::TypeWrapper<ROOT::Minuit2::MnUserParameterState>  t = jlModule.add_type<ROOT::Minuit2::MnUserParameterState>("ROOT!Minuit2!MnUserParameterState");
    type_ = std::unique_ptr<jlcxx::TypeWrapper<ROOT::Minuit2::MnUserParameterState>>(new jlcxx::TypeWrapper<ROOT::Minuit2::MnUserParameterState>(jlModule, t));
  }

  void add_methods() const{
    auto& t = *type_;
    t.template constructor<>(/*finalize=*/jlcxx::finalize_policy::yes);


    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnUserParameterState::MnUserParameterState(const ROOT::Minuit2::MnUserParameters &) (" __HERE__ ")");
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:49:4
    t.constructor<const ROOT::Minuit2::MnUserParameters &>(/*finalize=*/jlcxx::finalize_policy::yes);


    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnUserParameterState::MnUserParameterState(const ROOT::Minuit2::MnUserParameters &, const ROOT::Minuit2::MnUserCovariance &) (" __HERE__ ")");
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:56:4
    t.constructor<const ROOT::Minuit2::MnUserParameters &, const ROOT::Minuit2::MnUserCovariance &>(/*finalize=*/jlcxx::finalize_policy::yes);


    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnUserParameterState::MnUserParameterState(const ROOT::Minuit2::MinimumState &, double, const ROOT::Minuit2::MnUserTransformation &) (" __HERE__ ")");
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:59:4
    t.constructor<const ROOT::Minuit2::MinimumState &, double, const ROOT::Minuit2::MnUserTransformation &>(/*finalize=*/jlcxx::finalize_policy::yes);

    DEBUG_MSG("Adding wrapper for const ROOT::Minuit2::MnUserParameters & ROOT::Minuit2::MnUserParameterState::Parameters() (" __HERE__ ")");
    // signature to use in the veto list: const ROOT::Minuit2::MnUserParameters & ROOT::Minuit2::MnUserParameterState::Parameters()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:62:28
    t.method("Parameters", static_cast<const ROOT::Minuit2::MnUserParameters & (ROOT::Minuit2::MnUserParameterState::*)()  const>(&ROOT::Minuit2::MnUserParameterState::Parameters));

    DEBUG_MSG("Adding wrapper for const ROOT::Minuit2::MnUserCovariance & ROOT::Minuit2::MnUserParameterState::Covariance() (" __HERE__ ")");
    // signature to use in the veto list: const ROOT::Minuit2::MnUserCovariance & ROOT::Minuit2::MnUserParameterState::Covariance()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:63:28
    t.method("Covariance", static_cast<const ROOT::Minuit2::MnUserCovariance & (ROOT::Minuit2::MnUserParameterState::*)()  const>(&ROOT::Minuit2::MnUserParameterState::Covariance));

    DEBUG_MSG("Adding wrapper for const ROOT::Minuit2::MnGlobalCorrelationCoeff & ROOT::Minuit2::MnUserParameterState::GlobalCC() (" __HERE__ ")");
    // signature to use in the veto list: const ROOT::Minuit2::MnGlobalCorrelationCoeff & ROOT::Minuit2::MnUserParameterState::GlobalCC()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:64:36
    t.method("GlobalCC", static_cast<const ROOT::Minuit2::MnGlobalCorrelationCoeff & (ROOT::Minuit2::MnUserParameterState::*)()  const>(&ROOT::Minuit2::MnUserParameterState::GlobalCC));

    DEBUG_MSG("Adding wrapper for ROOT::Minuit2::MnUserCovariance ROOT::Minuit2::MnUserParameterState::Hessian() (" __HERE__ ")");
    // signature to use in the veto list: ROOT::Minuit2::MnUserCovariance ROOT::Minuit2::MnUserParameterState::Hessian()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:67:21
    t.method("Hessian", static_cast<ROOT::Minuit2::MnUserCovariance (ROOT::Minuit2::MnUserParameterState::*)()  const>(&ROOT::Minuit2::MnUserParameterState::Hessian));

    DEBUG_MSG("Adding wrapper for const std::vector<double> & ROOT::Minuit2::MnUserParameterState::IntParameters() (" __HERE__ ")");
    // signature to use in the veto list: const std::vector<double> & ROOT::Minuit2::MnUserParameterState::IntParameters()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:70:31
    t.method("IntParameters", static_cast<const std::vector<double> & (ROOT::Minuit2::MnUserParameterState::*)()  const>(&ROOT::Minuit2::MnUserParameterState::IntParameters));

    DEBUG_MSG("Adding wrapper for const ROOT::Minuit2::MnUserCovariance & ROOT::Minuit2::MnUserParameterState::IntCovariance() (" __HERE__ ")");
    // signature to use in the veto list: const ROOT::Minuit2::MnUserCovariance & ROOT::Minuit2::MnUserParameterState::IntCovariance()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:71:28
    t.method("IntCovariance", static_cast<const ROOT::Minuit2::MnUserCovariance & (ROOT::Minuit2::MnUserParameterState::*)()  const>(&ROOT::Minuit2::MnUserParameterState::IntCovariance));

    DEBUG_MSG("Adding wrapper for int ROOT::Minuit2::MnUserParameterState::CovarianceStatus() (" __HERE__ ")");
    // signature to use in the veto list: int ROOT::Minuit2::MnUserParameterState::CovarianceStatus()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:74:8
    t.method("CovarianceStatus", static_cast<int (ROOT::Minuit2::MnUserParameterState::*)()  const>(&ROOT::Minuit2::MnUserParameterState::CovarianceStatus));

    DEBUG_MSG("Adding wrapper for const ROOT::Minuit2::MnUserTransformation & ROOT::Minuit2::MnUserParameterState::Trafo() (" __HERE__ ")");
    // signature to use in the veto list: const ROOT::Minuit2::MnUserTransformation & ROOT::Minuit2::MnUserParameterState::Trafo()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:77:32
    t.method("Trafo", static_cast<const ROOT::Minuit2::MnUserTransformation & (ROOT::Minuit2::MnUserParameterState::*)()  const>(&ROOT::Minuit2::MnUserParameterState::Trafo));

    DEBUG_MSG("Adding wrapper for bool ROOT::Minuit2::MnUserParameterState::IsValid() (" __HERE__ ")");
    // signature to use in the veto list: bool ROOT::Minuit2::MnUserParameterState::IsValid()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:79:9
    t.method("IsValid", static_cast<bool (ROOT::Minuit2::MnUserParameterState::*)()  const>(&ROOT::Minuit2::MnUserParameterState::IsValid));

    DEBUG_MSG("Adding wrapper for bool ROOT::Minuit2::MnUserParameterState::HasCovariance() (" __HERE__ ")");
    // signature to use in the veto list: bool ROOT::Minuit2::MnUserParameterState::HasCovariance()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:80:9
    t.method("HasCovariance", static_cast<bool (ROOT::Minuit2::MnUserParameterState::*)()  const>(&ROOT::Minuit2::MnUserParameterState::HasCovariance));

    DEBUG_MSG("Adding wrapper for bool ROOT::Minuit2::MnUserParameterState::HasGlobalCC() (" __HERE__ ")");
    // signature to use in the veto list: bool ROOT::Minuit2::MnUserParameterState::HasGlobalCC()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:81:9
    t.method("HasGlobalCC", static_cast<bool (ROOT::Minuit2::MnUserParameterState::*)()  const>(&ROOT::Minuit2::MnUserParameterState::HasGlobalCC));

    DEBUG_MSG("Adding wrapper for double ROOT::Minuit2::MnUserParameterState::Fval() (" __HERE__ ")");
    // signature to use in the veto list: double ROOT::Minuit2::MnUserParameterState::Fval()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:83:11
    t.method("Fval", static_cast<double (ROOT::Minuit2::MnUserParameterState::*)()  const>(&ROOT::Minuit2::MnUserParameterState::Fval));

    DEBUG_MSG("Adding wrapper for double ROOT::Minuit2::MnUserParameterState::Edm() (" __HERE__ ")");
    // signature to use in the veto list: double ROOT::Minuit2::MnUserParameterState::Edm()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:84:11
    t.method("Edm", static_cast<double (ROOT::Minuit2::MnUserParameterState::*)()  const>(&ROOT::Minuit2::MnUserParameterState::Edm));

    DEBUG_MSG("Adding wrapper for unsigned int ROOT::Minuit2::MnUserParameterState::NFcn() (" __HERE__ ")");
    // signature to use in the veto list: unsigned int ROOT::Minuit2::MnUserParameterState::NFcn()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:85:17
    t.method("NFcn", static_cast<unsigned int (ROOT::Minuit2::MnUserParameterState::*)()  const>(&ROOT::Minuit2::MnUserParameterState::NFcn));

    DEBUG_MSG("Adding wrapper for const std::vector<ROOT::Minuit2::MinuitParameter> & ROOT::Minuit2::MnUserParameterState::MinuitParameters() (" __HERE__ ")");
    // signature to use in the veto list: const std::vector<ROOT::Minuit2::MinuitParameter> & ROOT::Minuit2::MnUserParameterState::MinuitParameters()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:91:55
    t.method("MinuitParameters", static_cast<const std::vector<ROOT::Minuit2::MinuitParameter> & (ROOT::Minuit2::MnUserParameterState::*)()  const>(&ROOT::Minuit2::MnUserParameterState::MinuitParameters));

    DEBUG_MSG("Adding wrapper for std::vector<double> ROOT::Minuit2::MnUserParameterState::Params() (" __HERE__ ")");
    // signature to use in the veto list: std::vector<double> ROOT::Minuit2::MnUserParameterState::Params()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:93:24
    t.method("Params", static_cast<std::vector<double> (ROOT::Minuit2::MnUserParameterState::*)()  const>(&ROOT::Minuit2::MnUserParameterState::Params));

    DEBUG_MSG("Adding wrapper for std::vector<double> ROOT::Minuit2::MnUserParameterState::Errors() (" __HERE__ ")");
    // signature to use in the veto list: std::vector<double> ROOT::Minuit2::MnUserParameterState::Errors()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:94:24
    t.method("Errors", static_cast<std::vector<double> (ROOT::Minuit2::MnUserParameterState::*)()  const>(&ROOT::Minuit2::MnUserParameterState::Errors));

    DEBUG_MSG("Adding wrapper for const ROOT::Minuit2::MinuitParameter & ROOT::Minuit2::MnUserParameterState::Parameter(unsigned int) (" __HERE__ ")");
    // signature to use in the veto list: const ROOT::Minuit2::MinuitParameter & ROOT::Minuit2::MnUserParameterState::Parameter(unsigned int)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:97:27
    t.method("Parameter", static_cast<const ROOT::Minuit2::MinuitParameter & (ROOT::Minuit2::MnUserParameterState::*)(unsigned int)  const>(&ROOT::Minuit2::MnUserParameterState::Parameter));

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnUserParameterState::Add(const std::string &, double, double) (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MnUserParameterState::Add(const std::string &, double, double)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:100:9
    t.method("Add", static_cast<void (ROOT::Minuit2::MnUserParameterState::*)(const std::string &, double, double) >(&ROOT::Minuit2::MnUserParameterState::Add));

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnUserParameterState::Add(const std::string &, double, double, double, double) (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MnUserParameterState::Add(const std::string &, double, double, double, double)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:102:9
    t.method("Add", static_cast<void (ROOT::Minuit2::MnUserParameterState::*)(const std::string &, double, double, double, double) >(&ROOT::Minuit2::MnUserParameterState::Add));

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnUserParameterState::Add(const std::string &, double) (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MnUserParameterState::Add(const std::string &, double)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:104:9
    t.method("Add", static_cast<void (ROOT::Minuit2::MnUserParameterState::*)(const std::string &, double) >(&ROOT::Minuit2::MnUserParameterState::Add));

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnUserParameterState::AddCovariance(const ROOT::Minuit2::MnUserCovariance &) (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MnUserParameterState::AddCovariance(const ROOT::Minuit2::MnUserCovariance &)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:107:9
    t.method("AddCovariance", static_cast<void (ROOT::Minuit2::MnUserParameterState::*)(const ROOT::Minuit2::MnUserCovariance &) >(&ROOT::Minuit2::MnUserParameterState::AddCovariance));

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnUserParameterState::Fix(unsigned int) (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MnUserParameterState::Fix(unsigned int)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:110:9
    t.method("Fix", static_cast<void (ROOT::Minuit2::MnUserParameterState::*)(unsigned int) >(&ROOT::Minuit2::MnUserParameterState::Fix));

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnUserParameterState::Release(unsigned int) (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MnUserParameterState::Release(unsigned int)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:111:9
    t.method("Release", static_cast<void (ROOT::Minuit2::MnUserParameterState::*)(unsigned int) >(&ROOT::Minuit2::MnUserParameterState::Release));

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnUserParameterState::RemoveLimits(unsigned int) (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MnUserParameterState::RemoveLimits(unsigned int)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:112:9
    t.method("RemoveLimits", static_cast<void (ROOT::Minuit2::MnUserParameterState::*)(unsigned int) >(&ROOT::Minuit2::MnUserParameterState::RemoveLimits));

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnUserParameterState::SetValue(unsigned int, double) (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MnUserParameterState::SetValue(unsigned int, double)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:113:9
    t.method("SetValue", static_cast<void (ROOT::Minuit2::MnUserParameterState::*)(unsigned int, double) >(&ROOT::Minuit2::MnUserParameterState::SetValue));

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnUserParameterState::SetError(unsigned int, double) (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MnUserParameterState::SetError(unsigned int, double)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:114:9
    t.method("SetError", static_cast<void (ROOT::Minuit2::MnUserParameterState::*)(unsigned int, double) >(&ROOT::Minuit2::MnUserParameterState::SetError));

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnUserParameterState::SetLimits(unsigned int, double, double) (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MnUserParameterState::SetLimits(unsigned int, double, double)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:115:9
    t.method("SetLimits", static_cast<void (ROOT::Minuit2::MnUserParameterState::*)(unsigned int, double, double) >(&ROOT::Minuit2::MnUserParameterState::SetLimits));

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnUserParameterState::SetUpperLimit(unsigned int, double) (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MnUserParameterState::SetUpperLimit(unsigned int, double)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:116:9
    t.method("SetUpperLimit", static_cast<void (ROOT::Minuit2::MnUserParameterState::*)(unsigned int, double) >(&ROOT::Minuit2::MnUserParameterState::SetUpperLimit));

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnUserParameterState::SetLowerLimit(unsigned int, double) (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MnUserParameterState::SetLowerLimit(unsigned int, double)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:117:9
    t.method("SetLowerLimit", static_cast<void (ROOT::Minuit2::MnUserParameterState::*)(unsigned int, double) >(&ROOT::Minuit2::MnUserParameterState::SetLowerLimit));

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnUserParameterState::SetName(unsigned int, const std::string &) (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MnUserParameterState::SetName(unsigned int, const std::string &)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:118:9
    t.method("SetName", static_cast<void (ROOT::Minuit2::MnUserParameterState::*)(unsigned int, const std::string &) >(&ROOT::Minuit2::MnUserParameterState::SetName));

    DEBUG_MSG("Adding wrapper for double ROOT::Minuit2::MnUserParameterState::Value(unsigned int) (" __HERE__ ")");
    // signature to use in the veto list: double ROOT::Minuit2::MnUserParameterState::Value(unsigned int)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:120:11
    t.method("Value", static_cast<double (ROOT::Minuit2::MnUserParameterState::*)(unsigned int)  const>(&ROOT::Minuit2::MnUserParameterState::Value));

    DEBUG_MSG("Adding wrapper for double ROOT::Minuit2::MnUserParameterState::Error(unsigned int) (" __HERE__ ")");
    // signature to use in the veto list: double ROOT::Minuit2::MnUserParameterState::Error(unsigned int)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:121:11
    t.method("Error", static_cast<double (ROOT::Minuit2::MnUserParameterState::*)(unsigned int)  const>(&ROOT::Minuit2::MnUserParameterState::Error));

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnUserParameterState::Fix(const std::string &) (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MnUserParameterState::Fix(const std::string &)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:124:9
    t.method("Fix", static_cast<void (ROOT::Minuit2::MnUserParameterState::*)(const std::string &) >(&ROOT::Minuit2::MnUserParameterState::Fix));

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnUserParameterState::Release(const std::string &) (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MnUserParameterState::Release(const std::string &)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:125:9
    t.method("Release", static_cast<void (ROOT::Minuit2::MnUserParameterState::*)(const std::string &) >(&ROOT::Minuit2::MnUserParameterState::Release));

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnUserParameterState::SetValue(const std::string &, double) (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MnUserParameterState::SetValue(const std::string &, double)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:126:9
    t.method("SetValue", static_cast<void (ROOT::Minuit2::MnUserParameterState::*)(const std::string &, double) >(&ROOT::Minuit2::MnUserParameterState::SetValue));

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnUserParameterState::SetError(const std::string &, double) (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MnUserParameterState::SetError(const std::string &, double)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:127:9
    t.method("SetError", static_cast<void (ROOT::Minuit2::MnUserParameterState::*)(const std::string &, double) >(&ROOT::Minuit2::MnUserParameterState::SetError));

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnUserParameterState::SetLimits(const std::string &, double, double) (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MnUserParameterState::SetLimits(const std::string &, double, double)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:128:9
    t.method("SetLimits", static_cast<void (ROOT::Minuit2::MnUserParameterState::*)(const std::string &, double, double) >(&ROOT::Minuit2::MnUserParameterState::SetLimits));

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnUserParameterState::SetUpperLimit(const std::string &, double) (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MnUserParameterState::SetUpperLimit(const std::string &, double)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:129:9
    t.method("SetUpperLimit", static_cast<void (ROOT::Minuit2::MnUserParameterState::*)(const std::string &, double) >(&ROOT::Minuit2::MnUserParameterState::SetUpperLimit));

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnUserParameterState::SetLowerLimit(const std::string &, double) (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MnUserParameterState::SetLowerLimit(const std::string &, double)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:130:9
    t.method("SetLowerLimit", static_cast<void (ROOT::Minuit2::MnUserParameterState::*)(const std::string &, double) >(&ROOT::Minuit2::MnUserParameterState::SetLowerLimit));

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnUserParameterState::RemoveLimits(const std::string &) (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MnUserParameterState::RemoveLimits(const std::string &)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:131:9
    t.method("RemoveLimits", static_cast<void (ROOT::Minuit2::MnUserParameterState::*)(const std::string &) >(&ROOT::Minuit2::MnUserParameterState::RemoveLimits));

    DEBUG_MSG("Adding wrapper for double ROOT::Minuit2::MnUserParameterState::Value(const std::string &) (" __HERE__ ")");
    // signature to use in the veto list: double ROOT::Minuit2::MnUserParameterState::Value(const std::string &)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:133:11
    t.method("Value", static_cast<double (ROOT::Minuit2::MnUserParameterState::*)(const std::string &)  const>(&ROOT::Minuit2::MnUserParameterState::Value));

    DEBUG_MSG("Adding wrapper for double ROOT::Minuit2::MnUserParameterState::Error(const std::string &) (" __HERE__ ")");
    // signature to use in the veto list: double ROOT::Minuit2::MnUserParameterState::Error(const std::string &)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:134:11
    t.method("Error", static_cast<double (ROOT::Minuit2::MnUserParameterState::*)(const std::string &)  const>(&ROOT::Minuit2::MnUserParameterState::Error));

    DEBUG_MSG("Adding wrapper for unsigned int ROOT::Minuit2::MnUserParameterState::Index(const std::string &) (" __HERE__ ")");
    // signature to use in the veto list: unsigned int ROOT::Minuit2::MnUserParameterState::Index(const std::string &)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:137:17
    t.method("Index", static_cast<unsigned int (ROOT::Minuit2::MnUserParameterState::*)(const std::string &)  const>(&ROOT::Minuit2::MnUserParameterState::Index));

    DEBUG_MSG("Adding wrapper for const std::string & ROOT::Minuit2::MnUserParameterState::GetName(unsigned int) (" __HERE__ ")");
    // signature to use in the veto list: const std::string & ROOT::Minuit2::MnUserParameterState::GetName(unsigned int)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:139:23
    t.method("GetName", static_cast<const std::string & (ROOT::Minuit2::MnUserParameterState::*)(unsigned int)  const>(&ROOT::Minuit2::MnUserParameterState::GetName));

    DEBUG_MSG("Adding wrapper for const char * ROOT::Minuit2::MnUserParameterState::Name(unsigned int) (" __HERE__ ")");
    // signature to use in the veto list: const char * ROOT::Minuit2::MnUserParameterState::Name(unsigned int)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:141:16
    t.method("Name", [](ROOT::Minuit2::MnUserParameterState const& a, unsigned int arg0) { return (std::string)a.Name(arg0); });
    t.method("Name", [](ROOT::Minuit2::MnUserParameterState const* a, unsigned int arg0) { return (std::string)a->Name(arg0); });

    DEBUG_MSG("Adding wrapper for double ROOT::Minuit2::MnUserParameterState::Int2ext(unsigned int, double) (" __HERE__ ")");
    // signature to use in the veto list: double ROOT::Minuit2::MnUserParameterState::Int2ext(unsigned int, double)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:144:11
    t.method("Int2ext", static_cast<double (ROOT::Minuit2::MnUserParameterState::*)(unsigned int, double)  const>(&ROOT::Minuit2::MnUserParameterState::Int2ext));

    DEBUG_MSG("Adding wrapper for double ROOT::Minuit2::MnUserParameterState::Ext2int(unsigned int, double) (" __HERE__ ")");
    // signature to use in the veto list: double ROOT::Minuit2::MnUserParameterState::Ext2int(unsigned int, double)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:145:11
    t.method("Ext2int", static_cast<double (ROOT::Minuit2::MnUserParameterState::*)(unsigned int, double)  const>(&ROOT::Minuit2::MnUserParameterState::Ext2int));

    DEBUG_MSG("Adding wrapper for unsigned int ROOT::Minuit2::MnUserParameterState::IntOfExt(unsigned int) (" __HERE__ ")");
    // signature to use in the veto list: unsigned int ROOT::Minuit2::MnUserParameterState::IntOfExt(unsigned int)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:146:17
    t.method("IntOfExt", static_cast<unsigned int (ROOT::Minuit2::MnUserParameterState::*)(unsigned int)  const>(&ROOT::Minuit2::MnUserParameterState::IntOfExt));

    DEBUG_MSG("Adding wrapper for unsigned int ROOT::Minuit2::MnUserParameterState::ExtOfInt(unsigned int) (" __HERE__ ")");
    // signature to use in the veto list: unsigned int ROOT::Minuit2::MnUserParameterState::ExtOfInt(unsigned int)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:147:17
    t.method("ExtOfInt", static_cast<unsigned int (ROOT::Minuit2::MnUserParameterState::*)(unsigned int)  const>(&ROOT::Minuit2::MnUserParameterState::ExtOfInt));

    DEBUG_MSG("Adding wrapper for unsigned int ROOT::Minuit2::MnUserParameterState::VariableParameters() (" __HERE__ ")");
    // signature to use in the veto list: unsigned int ROOT::Minuit2::MnUserParameterState::VariableParameters()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:148:17
    t.method("VariableParameters", static_cast<unsigned int (ROOT::Minuit2::MnUserParameterState::*)()  const>(&ROOT::Minuit2::MnUserParameterState::VariableParameters));

    DEBUG_MSG("Adding wrapper for const ROOT::Minuit2::MnMachinePrecision & ROOT::Minuit2::MnUserParameterState::Precision() (" __HERE__ ")");
    // signature to use in the veto list: const ROOT::Minuit2::MnMachinePrecision & ROOT::Minuit2::MnUserParameterState::Precision()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:149:30
    t.method("Precision", static_cast<const ROOT::Minuit2::MnMachinePrecision & (ROOT::Minuit2::MnUserParameterState::*)()  const>(&ROOT::Minuit2::MnUserParameterState::Precision));

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnUserParameterState::SetPrecision(double) (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MnUserParameterState::SetPrecision(double)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameterState.h:150:9
    t.method("SetPrecision", static_cast<void (ROOT::Minuit2::MnUserParameterState::*)(double) >(&ROOT::Minuit2::MnUserParameterState::SetPrecision));
  }

private:
  std::unique_ptr<jlcxx::TypeWrapper<ROOT::Minuit2::MnUserParameterState>> type_;
};
std::shared_ptr<Wrapper> newJlROOT_Minuit2_MnUserParameterState(jlcxx::Module& module){
  return std::shared_ptr<Wrapper>(new JlROOT_Minuit2_MnUserParameterState(module));
}
