// this file was auto-generated by wrapit v1.4.0-3-g14eb9a6
#include "Wrapper.h"

#include "jlMinuit2.h"
#include "dbg_msg.h"
#include "jlcxx/functions.hpp"
#include "jlcxx/stl.hpp"

namespace jlcxx {
  template<> struct IsMirroredType<ROOT::Minuit2::MnMigrad> : std::false_type { };
  template<> struct DefaultConstructible<ROOT::Minuit2::MnMigrad> : std::false_type { };
template<> struct SuperType<ROOT::Minuit2::MnMigrad> { typedef ROOT::Minuit2::MnApplication type; };
}

// Class generating the wrapper for type ROOT::Minuit2::MnMigrad
// signature to use in the veto file: ROOT::Minuit2::MnMigrad
struct JlROOT_Minuit2_MnMigrad: public Wrapper {

  JlROOT_Minuit2_MnMigrad(jlcxx::Module& jlModule): Wrapper(jlModule){
    DEBUG_MSG("Adding wrapper for type ROOT::Minuit2::MnMigrad (" __HERE__ ")");
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnMigrad.h:32:7
    jlcxx::TypeWrapper<ROOT::Minuit2::MnMigrad>  t = jlModule.add_type<ROOT::Minuit2::MnMigrad>("ROOT!Minuit2!MnMigrad",
      jlcxx::julia_base_type<ROOT::Minuit2::MnApplication>());
    type_ = std::unique_ptr<jlcxx::TypeWrapper<ROOT::Minuit2::MnMigrad>>(new jlcxx::TypeWrapper<ROOT::Minuit2::MnMigrad>(jlModule, t));
  }

  void add_methods() const{
    auto& t = *type_;


    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnMigrad::MnMigrad(const ROOT::Minuit2::FCNBase &, const ROOT::Minuit2::MnUserParameterState &, const ROOT::Minuit2::MnStrategy &) (" __HERE__ ")");
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnMigrad.h:36:4
    t.constructor<const ROOT::Minuit2::FCNBase &, const ROOT::Minuit2::MnUserParameterState &>(/*finalize=*/jlcxx::finalize_policy::yes);
    t.constructor<const ROOT::Minuit2::FCNBase &, const ROOT::Minuit2::MnUserParameterState &, const ROOT::Minuit2::MnStrategy &>(/*finalize=*/jlcxx::finalize_policy::yes);


    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnMigrad::MnMigrad(const ROOT::Minuit2::MnMigrad &) (" __HERE__ ")");
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnMigrad.h:42:4
    t.constructor<const ROOT::Minuit2::MnMigrad &>(/*finalize=*/jlcxx::finalize_policy::yes);

    DEBUG_MSG("Adding wrapper for ROOT::Minuit2::ModularFunctionMinimizer & ROOT::Minuit2::MnMigrad::Minimizer() (" __HERE__ ")");
    // signature to use in the veto list: ROOT::Minuit2::ModularFunctionMinimizer & ROOT::Minuit2::MnMigrad::Minimizer()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnMigrad.h:47:30
    t.method("Minimizer", [](ROOT::Minuit2::MnMigrad& a)->ROOT::Minuit2::ModularFunctionMinimizer & { return a.Minimizer(); });
    t.method("Minimizer", [](ROOT::Minuit2::MnMigrad* a)->ROOT::Minuit2::ModularFunctionMinimizer & { return a->Minimizer(); });

    DEBUG_MSG("Adding wrapper for const ROOT::Minuit2::ModularFunctionMinimizer & ROOT::Minuit2::MnMigrad::Minimizer() (" __HERE__ ")");
    // signature to use in the veto list: const ROOT::Minuit2::ModularFunctionMinimizer & ROOT::Minuit2::MnMigrad::Minimizer()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnMigrad.h:48:36
    t.method("Minimizer", [](ROOT::Minuit2::MnMigrad const& a)->const ROOT::Minuit2::ModularFunctionMinimizer & { return a.Minimizer(); });
    t.method("Minimizer", [](ROOT::Minuit2::MnMigrad const* a)->const ROOT::Minuit2::ModularFunctionMinimizer & { return a->Minimizer(); });
  }

private:
  std::unique_ptr<jlcxx::TypeWrapper<ROOT::Minuit2::MnMigrad>> type_;
};
std::shared_ptr<Wrapper> newJlROOT_Minuit2_MnMigrad(jlcxx::Module& module){
  return std::shared_ptr<Wrapper>(new JlROOT_Minuit2_MnMigrad(module));
}
