// this file was auto-generated by wrapit v1.4.0-3-g14eb9a6
#include "Wrapper.h"

#include "jlMinuit2.h"
#include "dbg_msg.h"
#include "jlcxx/functions.hpp"
#include "jlcxx/stl.hpp"

namespace jlcxx {
  template<> struct IsMirroredType<ROOT::Minuit2::MnUserParameters> : std::false_type { };
  template<> struct DefaultConstructible<ROOT::Minuit2::MnUserParameters> : std::false_type { };
}

// Class generating the wrapper for type ROOT::Minuit2::MnUserParameters
// signature to use in the veto file: ROOT::Minuit2::MnUserParameters
struct JlROOT_Minuit2_MnUserParameters: public Wrapper {

  JlROOT_Minuit2_MnUserParameters(jlcxx::Module& jlModule): Wrapper(jlModule){
    DEBUG_MSG("Adding wrapper for type ROOT::Minuit2::MnUserParameters (" __HERE__ ")");
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameters.h:36:7
    jlcxx::TypeWrapper<ROOT::Minuit2::MnUserParameters>  t = jlModule.add_type<ROOT::Minuit2::MnUserParameters>("ROOT!Minuit2!MnUserParameters");
    type_ = std::unique_ptr<jlcxx::TypeWrapper<ROOT::Minuit2::MnUserParameters>>(new jlcxx::TypeWrapper<ROOT::Minuit2::MnUserParameters>(jlModule, t));
  }

  void add_methods() const{
    auto& t = *type_;
    t.template constructor<>(/*finalize=*/jlcxx::finalize_policy::yes);


    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnUserParameters::MnUserParameters(const ROOT::Minuit2::MnUserParameters &) (" __HERE__ ")");
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameters.h:45:4
    t.constructor<const ROOT::Minuit2::MnUserParameters &>(/*finalize=*/jlcxx::finalize_policy::yes);

    DEBUG_MSG("Adding wrapper for ROOT::Minuit2::MnUserParameters & ROOT::Minuit2::MnUserParameters::operator=(const ROOT::Minuit2::MnUserParameters &) (" __HERE__ ")");
    // signature to use in the veto list: ROOT::Minuit2::MnUserParameters & ROOT::Minuit2::MnUserParameters::operator=(const ROOT::Minuit2::MnUserParameters &)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameters.h:47:22
    t.method("assign", [](ROOT::Minuit2::MnUserParameters& a, const ROOT::Minuit2::MnUserParameters & arg0)->ROOT::Minuit2::MnUserParameters & { return a.operator=(arg0); });
    t.method("assign", [](ROOT::Minuit2::MnUserParameters* a, const ROOT::Minuit2::MnUserParameters & arg0)->ROOT::Minuit2::MnUserParameters & { return a->operator=(arg0); });

    DEBUG_MSG("Adding wrapper for const ROOT::Minuit2::MnUserTransformation & ROOT::Minuit2::MnUserParameters::Trafo() (" __HERE__ ")");
    // signature to use in the veto list: const ROOT::Minuit2::MnUserTransformation & ROOT::Minuit2::MnUserParameters::Trafo()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameters.h:53:32
    t.method("Trafo", [](ROOT::Minuit2::MnUserParameters const& a)->const ROOT::Minuit2::MnUserTransformation & { return a.Trafo(); });
    t.method("Trafo", [](ROOT::Minuit2::MnUserParameters const* a)->const ROOT::Minuit2::MnUserTransformation & { return a->Trafo(); });

    DEBUG_MSG("Adding wrapper for unsigned int ROOT::Minuit2::MnUserParameters::VariableParameters() (" __HERE__ ")");
    // signature to use in the veto list: unsigned int ROOT::Minuit2::MnUserParameters::VariableParameters()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameters.h:55:17
    t.method("VariableParameters", [](ROOT::Minuit2::MnUserParameters const& a)->unsigned int { return a.VariableParameters(); });
    t.method("VariableParameters", [](ROOT::Minuit2::MnUserParameters const* a)->unsigned int { return a->VariableParameters(); });

    DEBUG_MSG("Adding wrapper for const std::vector<ROOT::Minuit2::MinuitParameter> & ROOT::Minuit2::MnUserParameters::Parameters() (" __HERE__ ")");
    // signature to use in the veto list: const std::vector<ROOT::Minuit2::MinuitParameter> & ROOT::Minuit2::MnUserParameters::Parameters()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameters.h:58:55
    t.method("Parameters", [](ROOT::Minuit2::MnUserParameters const& a)->const std::vector<ROOT::Minuit2::MinuitParameter> & { return a.Parameters(); });
    t.method("Parameters", [](ROOT::Minuit2::MnUserParameters const* a)->const std::vector<ROOT::Minuit2::MinuitParameter> & { return a->Parameters(); });

    DEBUG_MSG("Adding wrapper for std::vector<double> ROOT::Minuit2::MnUserParameters::Params() (" __HERE__ ")");
    // signature to use in the veto list: std::vector<double> ROOT::Minuit2::MnUserParameters::Params()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameters.h:61:24
    t.method("Params", [](ROOT::Minuit2::MnUserParameters const& a)->std::vector<double> { return a.Params(); });
    t.method("Params", [](ROOT::Minuit2::MnUserParameters const* a)->std::vector<double> { return a->Params(); });

    DEBUG_MSG("Adding wrapper for std::vector<double> ROOT::Minuit2::MnUserParameters::Errors() (" __HERE__ ")");
    // signature to use in the veto list: std::vector<double> ROOT::Minuit2::MnUserParameters::Errors()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameters.h:62:24
    t.method("Errors", [](ROOT::Minuit2::MnUserParameters const& a)->std::vector<double> { return a.Errors(); });
    t.method("Errors", [](ROOT::Minuit2::MnUserParameters const* a)->std::vector<double> { return a->Errors(); });

    DEBUG_MSG("Adding wrapper for const ROOT::Minuit2::MinuitParameter & ROOT::Minuit2::MnUserParameters::Parameter(unsigned int) (" __HERE__ ")");
    // signature to use in the veto list: const ROOT::Minuit2::MinuitParameter & ROOT::Minuit2::MnUserParameters::Parameter(unsigned int)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameters.h:65:27
    t.method("Parameter", [](ROOT::Minuit2::MnUserParameters const& a, unsigned int arg0)->const ROOT::Minuit2::MinuitParameter & { return a.Parameter(arg0); });
    t.method("Parameter", [](ROOT::Minuit2::MnUserParameters const* a, unsigned int arg0)->const ROOT::Minuit2::MinuitParameter & { return a->Parameter(arg0); });

    DEBUG_MSG("Adding wrapper for bool ROOT::Minuit2::MnUserParameters::Add(const std::string &, double, double) (" __HERE__ ")");
    // signature to use in the veto list: bool ROOT::Minuit2::MnUserParameters::Add(const std::string &, double, double)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameters.h:68:9
    t.method("Add", [](ROOT::Minuit2::MnUserParameters& a, const std::string & arg0, double arg1, double arg2)->bool { return a.Add(arg0, arg1, arg2); });
    t.method("Add", [](ROOT::Minuit2::MnUserParameters* a, const std::string & arg0, double arg1, double arg2)->bool { return a->Add(arg0, arg1, arg2); });

    DEBUG_MSG("Adding wrapper for bool ROOT::Minuit2::MnUserParameters::Add(const std::string &, double, double, double, double) (" __HERE__ ")");
    // signature to use in the veto list: bool ROOT::Minuit2::MnUserParameters::Add(const std::string &, double, double, double, double)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameters.h:70:9
    t.method("Add", [](ROOT::Minuit2::MnUserParameters& a, const std::string & arg0, double arg1, double arg2, double arg3, double arg4)->bool { return a.Add(arg0, arg1, arg2, arg3, arg4); });
    t.method("Add", [](ROOT::Minuit2::MnUserParameters* a, const std::string & arg0, double arg1, double arg2, double arg3, double arg4)->bool { return a->Add(arg0, arg1, arg2, arg3, arg4); });

    DEBUG_MSG("Adding wrapper for bool ROOT::Minuit2::MnUserParameters::Add(const std::string &, double) (" __HERE__ ")");
    // signature to use in the veto list: bool ROOT::Minuit2::MnUserParameters::Add(const std::string &, double)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameters.h:72:9
    t.method("Add", [](ROOT::Minuit2::MnUserParameters& a, const std::string & arg0, double arg1)->bool { return a.Add(arg0, arg1); });
    t.method("Add", [](ROOT::Minuit2::MnUserParameters* a, const std::string & arg0, double arg1)->bool { return a->Add(arg0, arg1); });

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnUserParameters::Fix(unsigned int) (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MnUserParameters::Fix(unsigned int)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameters.h:75:9
    t.method("Fix", [](ROOT::Minuit2::MnUserParameters& a, unsigned int arg0)->void { a.Fix(arg0); });
    t.method("Fix", [](ROOT::Minuit2::MnUserParameters* a, unsigned int arg0)->void { a->Fix(arg0); });

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnUserParameters::Release(unsigned int) (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MnUserParameters::Release(unsigned int)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameters.h:76:9
    t.method("Release", [](ROOT::Minuit2::MnUserParameters& a, unsigned int arg0)->void { a.Release(arg0); });
    t.method("Release", [](ROOT::Minuit2::MnUserParameters* a, unsigned int arg0)->void { a->Release(arg0); });

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnUserParameters::RemoveLimits(unsigned int) (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MnUserParameters::RemoveLimits(unsigned int)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameters.h:77:9
    t.method("RemoveLimits", [](ROOT::Minuit2::MnUserParameters& a, unsigned int arg0)->void { a.RemoveLimits(arg0); });
    t.method("RemoveLimits", [](ROOT::Minuit2::MnUserParameters* a, unsigned int arg0)->void { a->RemoveLimits(arg0); });

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnUserParameters::SetValue(unsigned int, double) (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MnUserParameters::SetValue(unsigned int, double)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameters.h:78:9
    t.method("SetValue", [](ROOT::Minuit2::MnUserParameters& a, unsigned int arg0, double arg1)->void { a.SetValue(arg0, arg1); });
    t.method("SetValue", [](ROOT::Minuit2::MnUserParameters* a, unsigned int arg0, double arg1)->void { a->SetValue(arg0, arg1); });

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnUserParameters::SetError(unsigned int, double) (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MnUserParameters::SetError(unsigned int, double)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameters.h:79:9
    t.method("SetError", [](ROOT::Minuit2::MnUserParameters& a, unsigned int arg0, double arg1)->void { a.SetError(arg0, arg1); });
    t.method("SetError", [](ROOT::Minuit2::MnUserParameters* a, unsigned int arg0, double arg1)->void { a->SetError(arg0, arg1); });

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnUserParameters::SetLimits(unsigned int, double, double) (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MnUserParameters::SetLimits(unsigned int, double, double)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameters.h:80:9
    t.method("SetLimits", [](ROOT::Minuit2::MnUserParameters& a, unsigned int arg0, double arg1, double arg2)->void { a.SetLimits(arg0, arg1, arg2); });
    t.method("SetLimits", [](ROOT::Minuit2::MnUserParameters* a, unsigned int arg0, double arg1, double arg2)->void { a->SetLimits(arg0, arg1, arg2); });

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnUserParameters::SetUpperLimit(unsigned int, double) (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MnUserParameters::SetUpperLimit(unsigned int, double)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameters.h:81:9
    t.method("SetUpperLimit", [](ROOT::Minuit2::MnUserParameters& a, unsigned int arg0, double arg1)->void { a.SetUpperLimit(arg0, arg1); });
    t.method("SetUpperLimit", [](ROOT::Minuit2::MnUserParameters* a, unsigned int arg0, double arg1)->void { a->SetUpperLimit(arg0, arg1); });

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnUserParameters::SetLowerLimit(unsigned int, double) (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MnUserParameters::SetLowerLimit(unsigned int, double)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameters.h:82:9
    t.method("SetLowerLimit", [](ROOT::Minuit2::MnUserParameters& a, unsigned int arg0, double arg1)->void { a.SetLowerLimit(arg0, arg1); });
    t.method("SetLowerLimit", [](ROOT::Minuit2::MnUserParameters* a, unsigned int arg0, double arg1)->void { a->SetLowerLimit(arg0, arg1); });

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnUserParameters::SetName(unsigned int, const std::string &) (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MnUserParameters::SetName(unsigned int, const std::string &)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameters.h:83:9
    t.method("SetName", [](ROOT::Minuit2::MnUserParameters& a, unsigned int arg0, const std::string & arg1)->void { a.SetName(arg0, arg1); });
    t.method("SetName", [](ROOT::Minuit2::MnUserParameters* a, unsigned int arg0, const std::string & arg1)->void { a->SetName(arg0, arg1); });

    DEBUG_MSG("Adding wrapper for double ROOT::Minuit2::MnUserParameters::Value(unsigned int) (" __HERE__ ")");
    // signature to use in the veto list: double ROOT::Minuit2::MnUserParameters::Value(unsigned int)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameters.h:85:11
    t.method("Value", [](ROOT::Minuit2::MnUserParameters const& a, unsigned int arg0)->double { return a.Value(arg0); });
    t.method("Value", [](ROOT::Minuit2::MnUserParameters const* a, unsigned int arg0)->double { return a->Value(arg0); });

    DEBUG_MSG("Adding wrapper for double ROOT::Minuit2::MnUserParameters::Error(unsigned int) (" __HERE__ ")");
    // signature to use in the veto list: double ROOT::Minuit2::MnUserParameters::Error(unsigned int)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameters.h:86:11
    t.method("Error", [](ROOT::Minuit2::MnUserParameters const& a, unsigned int arg0)->double { return a.Error(arg0); });
    t.method("Error", [](ROOT::Minuit2::MnUserParameters const* a, unsigned int arg0)->double { return a->Error(arg0); });

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnUserParameters::Fix(const std::string &) (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MnUserParameters::Fix(const std::string &)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameters.h:89:9
    t.method("Fix", [](ROOT::Minuit2::MnUserParameters& a, const std::string & arg0)->void { a.Fix(arg0); });
    t.method("Fix", [](ROOT::Minuit2::MnUserParameters* a, const std::string & arg0)->void { a->Fix(arg0); });

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnUserParameters::Release(const std::string &) (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MnUserParameters::Release(const std::string &)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameters.h:90:9
    t.method("Release", [](ROOT::Minuit2::MnUserParameters& a, const std::string & arg0)->void { a.Release(arg0); });
    t.method("Release", [](ROOT::Minuit2::MnUserParameters* a, const std::string & arg0)->void { a->Release(arg0); });

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnUserParameters::SetValue(const std::string &, double) (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MnUserParameters::SetValue(const std::string &, double)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameters.h:91:9
    t.method("SetValue", [](ROOT::Minuit2::MnUserParameters& a, const std::string & arg0, double arg1)->void { a.SetValue(arg0, arg1); });
    t.method("SetValue", [](ROOT::Minuit2::MnUserParameters* a, const std::string & arg0, double arg1)->void { a->SetValue(arg0, arg1); });

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnUserParameters::SetError(const std::string &, double) (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MnUserParameters::SetError(const std::string &, double)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameters.h:92:9
    t.method("SetError", [](ROOT::Minuit2::MnUserParameters& a, const std::string & arg0, double arg1)->void { a.SetError(arg0, arg1); });
    t.method("SetError", [](ROOT::Minuit2::MnUserParameters* a, const std::string & arg0, double arg1)->void { a->SetError(arg0, arg1); });

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnUserParameters::SetLimits(const std::string &, double, double) (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MnUserParameters::SetLimits(const std::string &, double, double)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameters.h:93:9
    t.method("SetLimits", [](ROOT::Minuit2::MnUserParameters& a, const std::string & arg0, double arg1, double arg2)->void { a.SetLimits(arg0, arg1, arg2); });
    t.method("SetLimits", [](ROOT::Minuit2::MnUserParameters* a, const std::string & arg0, double arg1, double arg2)->void { a->SetLimits(arg0, arg1, arg2); });

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnUserParameters::SetUpperLimit(const std::string &, double) (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MnUserParameters::SetUpperLimit(const std::string &, double)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameters.h:94:9
    t.method("SetUpperLimit", [](ROOT::Minuit2::MnUserParameters& a, const std::string & arg0, double arg1)->void { a.SetUpperLimit(arg0, arg1); });
    t.method("SetUpperLimit", [](ROOT::Minuit2::MnUserParameters* a, const std::string & arg0, double arg1)->void { a->SetUpperLimit(arg0, arg1); });

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnUserParameters::SetLowerLimit(const std::string &, double) (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MnUserParameters::SetLowerLimit(const std::string &, double)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameters.h:95:9
    t.method("SetLowerLimit", [](ROOT::Minuit2::MnUserParameters& a, const std::string & arg0, double arg1)->void { a.SetLowerLimit(arg0, arg1); });
    t.method("SetLowerLimit", [](ROOT::Minuit2::MnUserParameters* a, const std::string & arg0, double arg1)->void { a->SetLowerLimit(arg0, arg1); });

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnUserParameters::RemoveLimits(const std::string &) (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MnUserParameters::RemoveLimits(const std::string &)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameters.h:96:9
    t.method("RemoveLimits", [](ROOT::Minuit2::MnUserParameters& a, const std::string & arg0)->void { a.RemoveLimits(arg0); });
    t.method("RemoveLimits", [](ROOT::Minuit2::MnUserParameters* a, const std::string & arg0)->void { a->RemoveLimits(arg0); });

    DEBUG_MSG("Adding wrapper for double ROOT::Minuit2::MnUserParameters::Value(const std::string &) (" __HERE__ ")");
    // signature to use in the veto list: double ROOT::Minuit2::MnUserParameters::Value(const std::string &)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameters.h:98:11
    t.method("Value", [](ROOT::Minuit2::MnUserParameters const& a, const std::string & arg0)->double { return a.Value(arg0); });
    t.method("Value", [](ROOT::Minuit2::MnUserParameters const* a, const std::string & arg0)->double { return a->Value(arg0); });

    DEBUG_MSG("Adding wrapper for double ROOT::Minuit2::MnUserParameters::Error(const std::string &) (" __HERE__ ")");
    // signature to use in the veto list: double ROOT::Minuit2::MnUserParameters::Error(const std::string &)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameters.h:99:11
    t.method("Error", [](ROOT::Minuit2::MnUserParameters const& a, const std::string & arg0)->double { return a.Error(arg0); });
    t.method("Error", [](ROOT::Minuit2::MnUserParameters const* a, const std::string & arg0)->double { return a->Error(arg0); });

    DEBUG_MSG("Adding wrapper for unsigned int ROOT::Minuit2::MnUserParameters::Index(const std::string &) (" __HERE__ ")");
    // signature to use in the veto list: unsigned int ROOT::Minuit2::MnUserParameters::Index(const std::string &)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameters.h:102:17
    t.method("Index", [](ROOT::Minuit2::MnUserParameters const& a, const std::string & arg0)->unsigned int { return a.Index(arg0); });
    t.method("Index", [](ROOT::Minuit2::MnUserParameters const* a, const std::string & arg0)->unsigned int { return a->Index(arg0); });

    DEBUG_MSG("Adding wrapper for const std::string & ROOT::Minuit2::MnUserParameters::GetName(unsigned int) (" __HERE__ ")");
    // signature to use in the veto list: const std::string & ROOT::Minuit2::MnUserParameters::GetName(unsigned int)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameters.h:104:23
    t.method("GetName", [](ROOT::Minuit2::MnUserParameters const& a, unsigned int arg0)->const std::string & { return a.GetName(arg0); });
    t.method("GetName", [](ROOT::Minuit2::MnUserParameters const* a, unsigned int arg0)->const std::string & { return a->GetName(arg0); });

    DEBUG_MSG("Adding wrapper for const char * ROOT::Minuit2::MnUserParameters::Name(unsigned int) (" __HERE__ ")");
    // signature to use in the veto list: const char * ROOT::Minuit2::MnUserParameters::Name(unsigned int)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameters.h:106:16
    t.method("Name", [](ROOT::Minuit2::MnUserParameters const& a, unsigned int arg0) { return (std::string)a.Name(arg0); });
    t.method("Name", [](ROOT::Minuit2::MnUserParameters const* a, unsigned int arg0) { return (std::string)a->Name(arg0); });

    DEBUG_MSG("Adding wrapper for const ROOT::Minuit2::MnMachinePrecision & ROOT::Minuit2::MnUserParameters::Precision() (" __HERE__ ")");
    // signature to use in the veto list: const ROOT::Minuit2::MnMachinePrecision & ROOT::Minuit2::MnUserParameters::Precision()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameters.h:108:30
    t.method("Precision", [](ROOT::Minuit2::MnUserParameters const& a)->const ROOT::Minuit2::MnMachinePrecision & { return a.Precision(); });
    t.method("Precision", [](ROOT::Minuit2::MnUserParameters const* a)->const ROOT::Minuit2::MnMachinePrecision & { return a->Precision(); });

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnUserParameters::SetPrecision(double) (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MnUserParameters::SetPrecision(double)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnUserParameters.h:109:9
    t.method("SetPrecision", [](ROOT::Minuit2::MnUserParameters& a, double arg0)->void { a.SetPrecision(arg0); });
    t.method("SetPrecision", [](ROOT::Minuit2::MnUserParameters* a, double arg0)->void { a->SetPrecision(arg0); });
  }

private:
  std::unique_ptr<jlcxx::TypeWrapper<ROOT::Minuit2::MnUserParameters>> type_;
};
std::shared_ptr<Wrapper> newJlROOT_Minuit2_MnUserParameters(jlcxx::Module& module){
  return std::shared_ptr<Wrapper>(new JlROOT_Minuit2_MnUserParameters(module));
}
