// this file was auto-generated by wrapit v1.4.0-3-g14eb9a6
#include "Wrapper.h"

#include "jlMinuit2.h"
#include "dbg_msg.h"
#include "jlcxx/functions.hpp"
#include "jlcxx/stl.hpp"

namespace jlcxx {
  template<> struct IsMirroredType<ROOT::Minuit2::MnStrategy> : std::false_type { };
  template<> struct DefaultConstructible<ROOT::Minuit2::MnStrategy> : std::false_type { };
}

// Class generating the wrapper for type ROOT::Minuit2::MnStrategy
// signature to use in the veto file: ROOT::Minuit2::MnStrategy
struct JlROOT_Minuit2_MnStrategy: public Wrapper {

  JlROOT_Minuit2_MnStrategy(jlcxx::Module& jlModule): Wrapper(jlModule){
    DEBUG_MSG("Adding wrapper for type ROOT::Minuit2::MnStrategy (" __HERE__ ")");
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnStrategy.h:27:7
    jlcxx::TypeWrapper<ROOT::Minuit2::MnStrategy>  t = jlModule.add_type<ROOT::Minuit2::MnStrategy>("ROOT!Minuit2!MnStrategy");
    type_ = std::unique_ptr<jlcxx::TypeWrapper<ROOT::Minuit2::MnStrategy>>(new jlcxx::TypeWrapper<ROOT::Minuit2::MnStrategy>(jlModule, t));
  }

  void add_methods() const{
    auto& t = *type_;
    t.template constructor<>(/*finalize=*/jlcxx::finalize_policy::yes);


    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnStrategy::MnStrategy(unsigned int) (" __HERE__ ")");
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnStrategy.h:34:13
    t.constructor<unsigned int>(/*finalize=*/jlcxx::finalize_policy::yes);

    DEBUG_MSG("Adding wrapper for unsigned int ROOT::Minuit2::MnStrategy::Strategy() (" __HERE__ ")");
    // signature to use in the veto list: unsigned int ROOT::Minuit2::MnStrategy::Strategy()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnStrategy.h:38:17
    t.method("Strategy", [](ROOT::Minuit2::MnStrategy const& a)->unsigned int { return a.Strategy(); });
    t.method("Strategy", [](ROOT::Minuit2::MnStrategy const* a)->unsigned int { return a->Strategy(); });

    DEBUG_MSG("Adding wrapper for unsigned int ROOT::Minuit2::MnStrategy::GradientNCycles() (" __HERE__ ")");
    // signature to use in the veto list: unsigned int ROOT::Minuit2::MnStrategy::GradientNCycles()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnStrategy.h:40:17
    t.method("GradientNCycles", [](ROOT::Minuit2::MnStrategy const& a)->unsigned int { return a.GradientNCycles(); });
    t.method("GradientNCycles", [](ROOT::Minuit2::MnStrategy const* a)->unsigned int { return a->GradientNCycles(); });

    DEBUG_MSG("Adding wrapper for double ROOT::Minuit2::MnStrategy::GradientStepTolerance() (" __HERE__ ")");
    // signature to use in the veto list: double ROOT::Minuit2::MnStrategy::GradientStepTolerance()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnStrategy.h:41:11
    t.method("GradientStepTolerance", [](ROOT::Minuit2::MnStrategy const& a)->double { return a.GradientStepTolerance(); });
    t.method("GradientStepTolerance", [](ROOT::Minuit2::MnStrategy const* a)->double { return a->GradientStepTolerance(); });

    DEBUG_MSG("Adding wrapper for double ROOT::Minuit2::MnStrategy::GradientTolerance() (" __HERE__ ")");
    // signature to use in the veto list: double ROOT::Minuit2::MnStrategy::GradientTolerance()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnStrategy.h:42:11
    t.method("GradientTolerance", [](ROOT::Minuit2::MnStrategy const& a)->double { return a.GradientTolerance(); });
    t.method("GradientTolerance", [](ROOT::Minuit2::MnStrategy const* a)->double { return a->GradientTolerance(); });

    DEBUG_MSG("Adding wrapper for unsigned int ROOT::Minuit2::MnStrategy::HessianNCycles() (" __HERE__ ")");
    // signature to use in the veto list: unsigned int ROOT::Minuit2::MnStrategy::HessianNCycles()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnStrategy.h:44:17
    t.method("HessianNCycles", [](ROOT::Minuit2::MnStrategy const& a)->unsigned int { return a.HessianNCycles(); });
    t.method("HessianNCycles", [](ROOT::Minuit2::MnStrategy const* a)->unsigned int { return a->HessianNCycles(); });

    DEBUG_MSG("Adding wrapper for double ROOT::Minuit2::MnStrategy::HessianStepTolerance() (" __HERE__ ")");
    // signature to use in the veto list: double ROOT::Minuit2::MnStrategy::HessianStepTolerance()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnStrategy.h:45:11
    t.method("HessianStepTolerance", [](ROOT::Minuit2::MnStrategy const& a)->double { return a.HessianStepTolerance(); });
    t.method("HessianStepTolerance", [](ROOT::Minuit2::MnStrategy const* a)->double { return a->HessianStepTolerance(); });

    DEBUG_MSG("Adding wrapper for double ROOT::Minuit2::MnStrategy::HessianG2Tolerance() (" __HERE__ ")");
    // signature to use in the veto list: double ROOT::Minuit2::MnStrategy::HessianG2Tolerance()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnStrategy.h:46:11
    t.method("HessianG2Tolerance", [](ROOT::Minuit2::MnStrategy const& a)->double { return a.HessianG2Tolerance(); });
    t.method("HessianG2Tolerance", [](ROOT::Minuit2::MnStrategy const* a)->double { return a->HessianG2Tolerance(); });

    DEBUG_MSG("Adding wrapper for unsigned int ROOT::Minuit2::MnStrategy::HessianGradientNCycles() (" __HERE__ ")");
    // signature to use in the veto list: unsigned int ROOT::Minuit2::MnStrategy::HessianGradientNCycles()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnStrategy.h:47:17
    t.method("HessianGradientNCycles", [](ROOT::Minuit2::MnStrategy const& a)->unsigned int { return a.HessianGradientNCycles(); });
    t.method("HessianGradientNCycles", [](ROOT::Minuit2::MnStrategy const* a)->unsigned int { return a->HessianGradientNCycles(); });

    DEBUG_MSG("Adding wrapper for unsigned int ROOT::Minuit2::MnStrategy::HessianCentralFDMixedDerivatives() (" __HERE__ ")");
    // signature to use in the veto list: unsigned int ROOT::Minuit2::MnStrategy::HessianCentralFDMixedDerivatives()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnStrategy.h:48:17
    t.method("HessianCentralFDMixedDerivatives", [](ROOT::Minuit2::MnStrategy const& a)->unsigned int { return a.HessianCentralFDMixedDerivatives(); });
    t.method("HessianCentralFDMixedDerivatives", [](ROOT::Minuit2::MnStrategy const* a)->unsigned int { return a->HessianCentralFDMixedDerivatives(); });

    DEBUG_MSG("Adding wrapper for unsigned int ROOT::Minuit2::MnStrategy::HessianForcePosDef() (" __HERE__ ")");
    // signature to use in the veto list: unsigned int ROOT::Minuit2::MnStrategy::HessianForcePosDef()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnStrategy.h:49:17
    t.method("HessianForcePosDef", [](ROOT::Minuit2::MnStrategy const& a)->unsigned int { return a.HessianForcePosDef(); });
    t.method("HessianForcePosDef", [](ROOT::Minuit2::MnStrategy const* a)->unsigned int { return a->HessianForcePosDef(); });

    DEBUG_MSG("Adding wrapper for int ROOT::Minuit2::MnStrategy::StorageLevel() (" __HERE__ ")");
    // signature to use in the veto list: int ROOT::Minuit2::MnStrategy::StorageLevel()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnStrategy.h:51:8
    t.method("StorageLevel", [](ROOT::Minuit2::MnStrategy const& a)->int { return a.StorageLevel(); });
    t.method("StorageLevel", [](ROOT::Minuit2::MnStrategy const* a)->int { return a->StorageLevel(); });

    DEBUG_MSG("Adding wrapper for bool ROOT::Minuit2::MnStrategy::IsLow() (" __HERE__ ")");
    // signature to use in the veto list: bool ROOT::Minuit2::MnStrategy::IsLow()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnStrategy.h:53:9
    t.method("IsLow", [](ROOT::Minuit2::MnStrategy const& a)->bool { return a.IsLow(); });
    t.method("IsLow", [](ROOT::Minuit2::MnStrategy const* a)->bool { return a->IsLow(); });

    DEBUG_MSG("Adding wrapper for bool ROOT::Minuit2::MnStrategy::IsMedium() (" __HERE__ ")");
    // signature to use in the veto list: bool ROOT::Minuit2::MnStrategy::IsMedium()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnStrategy.h:54:9
    t.method("IsMedium", [](ROOT::Minuit2::MnStrategy const& a)->bool { return a.IsMedium(); });
    t.method("IsMedium", [](ROOT::Minuit2::MnStrategy const* a)->bool { return a->IsMedium(); });

    DEBUG_MSG("Adding wrapper for bool ROOT::Minuit2::MnStrategy::IsHigh() (" __HERE__ ")");
    // signature to use in the veto list: bool ROOT::Minuit2::MnStrategy::IsHigh()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnStrategy.h:55:9
    t.method("IsHigh", [](ROOT::Minuit2::MnStrategy const& a)->bool { return a.IsHigh(); });
    t.method("IsHigh", [](ROOT::Minuit2::MnStrategy const* a)->bool { return a->IsHigh(); });

    DEBUG_MSG("Adding wrapper for bool ROOT::Minuit2::MnStrategy::IsVeryHigh() (" __HERE__ ")");
    // signature to use in the veto list: bool ROOT::Minuit2::MnStrategy::IsVeryHigh()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnStrategy.h:56:9
    t.method("IsVeryHigh", [](ROOT::Minuit2::MnStrategy const& a)->bool { return a.IsVeryHigh(); });
    t.method("IsVeryHigh", [](ROOT::Minuit2::MnStrategy const* a)->bool { return a->IsVeryHigh(); });

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnStrategy::SetLowStrategy() (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MnStrategy::SetLowStrategy()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnStrategy.h:58:9
    t.method("SetLowStrategy", [](ROOT::Minuit2::MnStrategy& a)->void { a.SetLowStrategy(); });
    t.method("SetLowStrategy", [](ROOT::Minuit2::MnStrategy* a)->void { a->SetLowStrategy(); });

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnStrategy::SetMediumStrategy() (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MnStrategy::SetMediumStrategy()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnStrategy.h:59:9
    t.method("SetMediumStrategy", [](ROOT::Minuit2::MnStrategy& a)->void { a.SetMediumStrategy(); });
    t.method("SetMediumStrategy", [](ROOT::Minuit2::MnStrategy* a)->void { a->SetMediumStrategy(); });

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnStrategy::SetHighStrategy() (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MnStrategy::SetHighStrategy()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnStrategy.h:60:9
    t.method("SetHighStrategy", [](ROOT::Minuit2::MnStrategy& a)->void { a.SetHighStrategy(); });
    t.method("SetHighStrategy", [](ROOT::Minuit2::MnStrategy* a)->void { a->SetHighStrategy(); });

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnStrategy::SetVeryHighStrategy() (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MnStrategy::SetVeryHighStrategy()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnStrategy.h:61:9
    t.method("SetVeryHighStrategy", [](ROOT::Minuit2::MnStrategy& a)->void { a.SetVeryHighStrategy(); });
    t.method("SetVeryHighStrategy", [](ROOT::Minuit2::MnStrategy* a)->void { a->SetVeryHighStrategy(); });

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnStrategy::SetGradientNCycles(unsigned int) (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MnStrategy::SetGradientNCycles(unsigned int)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnStrategy.h:63:9
    t.method("SetGradientNCycles", [](ROOT::Minuit2::MnStrategy& a, unsigned int arg0)->void { a.SetGradientNCycles(arg0); });
    t.method("SetGradientNCycles", [](ROOT::Minuit2::MnStrategy* a, unsigned int arg0)->void { a->SetGradientNCycles(arg0); });

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnStrategy::SetGradientStepTolerance(double) (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MnStrategy::SetGradientStepTolerance(double)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnStrategy.h:64:9
    t.method("SetGradientStepTolerance", [](ROOT::Minuit2::MnStrategy& a, double arg0)->void { a.SetGradientStepTolerance(arg0); });
    t.method("SetGradientStepTolerance", [](ROOT::Minuit2::MnStrategy* a, double arg0)->void { a->SetGradientStepTolerance(arg0); });

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnStrategy::SetGradientTolerance(double) (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MnStrategy::SetGradientTolerance(double)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnStrategy.h:65:9
    t.method("SetGradientTolerance", [](ROOT::Minuit2::MnStrategy& a, double arg0)->void { a.SetGradientTolerance(arg0); });
    t.method("SetGradientTolerance", [](ROOT::Minuit2::MnStrategy* a, double arg0)->void { a->SetGradientTolerance(arg0); });

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnStrategy::SetHessianNCycles(unsigned int) (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MnStrategy::SetHessianNCycles(unsigned int)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnStrategy.h:67:9
    t.method("SetHessianNCycles", [](ROOT::Minuit2::MnStrategy& a, unsigned int arg0)->void { a.SetHessianNCycles(arg0); });
    t.method("SetHessianNCycles", [](ROOT::Minuit2::MnStrategy* a, unsigned int arg0)->void { a->SetHessianNCycles(arg0); });

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnStrategy::SetHessianStepTolerance(double) (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MnStrategy::SetHessianStepTolerance(double)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnStrategy.h:68:9
    t.method("SetHessianStepTolerance", [](ROOT::Minuit2::MnStrategy& a, double arg0)->void { a.SetHessianStepTolerance(arg0); });
    t.method("SetHessianStepTolerance", [](ROOT::Minuit2::MnStrategy* a, double arg0)->void { a->SetHessianStepTolerance(arg0); });

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnStrategy::SetHessianG2Tolerance(double) (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MnStrategy::SetHessianG2Tolerance(double)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnStrategy.h:69:9
    t.method("SetHessianG2Tolerance", [](ROOT::Minuit2::MnStrategy& a, double arg0)->void { a.SetHessianG2Tolerance(arg0); });
    t.method("SetHessianG2Tolerance", [](ROOT::Minuit2::MnStrategy* a, double arg0)->void { a->SetHessianG2Tolerance(arg0); });

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnStrategy::SetHessianGradientNCycles(unsigned int) (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MnStrategy::SetHessianGradientNCycles(unsigned int)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnStrategy.h:70:9
    t.method("SetHessianGradientNCycles", [](ROOT::Minuit2::MnStrategy& a, unsigned int arg0)->void { a.SetHessianGradientNCycles(arg0); });
    t.method("SetHessianGradientNCycles", [](ROOT::Minuit2::MnStrategy* a, unsigned int arg0)->void { a->SetHessianGradientNCycles(arg0); });

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnStrategy::SetHessianCentralFDMixedDerivatives(unsigned int) (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MnStrategy::SetHessianCentralFDMixedDerivatives(unsigned int)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnStrategy.h:74:9
    t.method("SetHessianCentralFDMixedDerivatives", [](ROOT::Minuit2::MnStrategy& a, unsigned int arg0)->void { a.SetHessianCentralFDMixedDerivatives(arg0); });
    t.method("SetHessianCentralFDMixedDerivatives", [](ROOT::Minuit2::MnStrategy* a, unsigned int arg0)->void { a->SetHessianCentralFDMixedDerivatives(arg0); });

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnStrategy::SetHessianForcePosDef(unsigned int) (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MnStrategy::SetHessianForcePosDef(unsigned int)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnStrategy.h:78:9
    t.method("SetHessianForcePosDef", [](ROOT::Minuit2::MnStrategy& a, unsigned int arg0)->void { a.SetHessianForcePosDef(arg0); });
    t.method("SetHessianForcePosDef", [](ROOT::Minuit2::MnStrategy* a, unsigned int arg0)->void { a->SetHessianForcePosDef(arg0); });

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnStrategy::SetStorageLevel(unsigned int) (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MnStrategy::SetStorageLevel(unsigned int)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnStrategy.h:82:9
    t.method("SetStorageLevel", [](ROOT::Minuit2::MnStrategy& a, unsigned int arg0)->void { a.SetStorageLevel(arg0); });
    t.method("SetStorageLevel", [](ROOT::Minuit2::MnStrategy* a, unsigned int arg0)->void { a->SetStorageLevel(arg0); });
  }

private:
  std::unique_ptr<jlcxx::TypeWrapper<ROOT::Minuit2::MnStrategy>> type_;
};
std::shared_ptr<Wrapper> newJlROOT_Minuit2_MnStrategy(jlcxx::Module& module){
  return std::shared_ptr<Wrapper>(new JlROOT_Minuit2_MnStrategy(module));
}
