// this file was auto-generated by wrapit v1.4.0-3-g14eb9a6
#include "Wrapper.h"

#include "jlMinuit2.h"
#include "dbg_msg.h"
#include "jlcxx/functions.hpp"
#include "jlcxx/stl.hpp"

namespace jlcxx {
  template<> struct IsMirroredType<ROOT::Minuit2::MnPrint::Oneline> : std::false_type { };
  template<> struct DefaultConstructible<ROOT::Minuit2::MnPrint::Oneline> : std::false_type { };
}

// Class generating the wrapper for type ROOT::Minuit2::MnPrint::Oneline
// signature to use in the veto file: ROOT::Minuit2::MnPrint::Oneline
struct JlROOT_Minuit2_MnPrint_Oneline: public Wrapper {

  JlROOT_Minuit2_MnPrint_Oneline(jlcxx::Module& jlModule): Wrapper(jlModule){
    DEBUG_MSG("Adding wrapper for type ROOT::Minuit2::MnPrint::Oneline (" __HERE__ ")");
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnPrint.h:86:10
    jlcxx::TypeWrapper<ROOT::Minuit2::MnPrint::Oneline>  t = jlModule.add_type<ROOT::Minuit2::MnPrint::Oneline>("ROOT!Minuit2!MnPrint!Oneline");
    type_ = std::unique_ptr<jlcxx::TypeWrapper<ROOT::Minuit2::MnPrint::Oneline>>(new jlcxx::TypeWrapper<ROOT::Minuit2::MnPrint::Oneline>(jlModule, t));
  }

  void add_methods() const{
    auto& t = *type_;


    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnPrint::Oneline::Oneline(double, double, int, int) (" __HERE__ ")");
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnPrint.h:88:7
    t.constructor<double, double, int>(/*finalize=*/jlcxx::finalize_policy::yes);
    t.constructor<double, double, int, int>(/*finalize=*/jlcxx::finalize_policy::yes);


    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnPrint::Oneline::Oneline(const ROOT::Minuit2::MinimumState &, int) (" __HERE__ ")");
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnPrint.h:89:7
    t.constructor<const ROOT::Minuit2::MinimumState &>(/*finalize=*/jlcxx::finalize_policy::yes);
    t.constructor<const ROOT::Minuit2::MinimumState &, int>(/*finalize=*/jlcxx::finalize_policy::yes);


    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnPrint::Oneline::Oneline(const ROOT::Minuit2::FunctionMinimum &, int) (" __HERE__ ")");
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnPrint.h:90:7
    t.constructor<const ROOT::Minuit2::FunctionMinimum &>(/*finalize=*/jlcxx::finalize_policy::yes);
    t.constructor<const ROOT::Minuit2::FunctionMinimum &, int>(/*finalize=*/jlcxx::finalize_policy::yes);
  }

private:
  std::unique_ptr<jlcxx::TypeWrapper<ROOT::Minuit2::MnPrint::Oneline>> type_;
};
std::shared_ptr<Wrapper> newJlROOT_Minuit2_MnPrint_Oneline(jlcxx::Module& module){
  return std::shared_ptr<Wrapper>(new JlROOT_Minuit2_MnPrint_Oneline(module));
}
