// this file was auto-generated by wrapit 5168a24-dirty
#include "Wrapper.h"

#include "jlMinuit2.h"
#include "dbg_msg.h"
#include "jlcxx/functions.hpp"
#include "jlcxx/stl.hpp"

namespace jlcxx {
  template<> struct IsMirroredType<ROOT::Minuit2::MinuitParameter> : std::false_type { };
  template<> struct DefaultConstructible<ROOT::Minuit2::MinuitParameter> : std::false_type { };
}

// Class generating the wrapper for type ROOT::Minuit2::MinuitParameter
// signature to use in the veto file: ROOT::Minuit2::MinuitParameter
struct JlROOT_Minuit2_MinuitParameter: public Wrapper {

  JlROOT_Minuit2_MinuitParameter(jlcxx::Module& jlModule): Wrapper(jlModule){
    DEBUG_MSG("Adding wrapper for type ROOT::Minuit2::MinuitParameter (" __HERE__ ")");
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MinuitParameter.h:33:7
    jlcxx::TypeWrapper<ROOT::Minuit2::MinuitParameter>  t = jlModule.add_type<ROOT::Minuit2::MinuitParameter>("ROOT!Minuit2!MinuitParameter");
    type_ = std::unique_ptr<jlcxx::TypeWrapper<ROOT::Minuit2::MinuitParameter>>(new jlcxx::TypeWrapper<ROOT::Minuit2::MinuitParameter>(jlModule, t));
  }

  void add_methods() const{
    auto& t = *type_;
    t.template constructor<>(/*finalize=*/jlcxx::finalize_policy::yes);


    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MinuitParameter::MinuitParameter(unsigned int, const std::string &, double) (" __HERE__ ")");
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MinuitParameter.h:44:4
    t.constructor<unsigned int, const std::string &, double>(/*finalize=*/jlcxx::finalize_policy::yes);


    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MinuitParameter::MinuitParameter(unsigned int, const std::string &, double, double) (" __HERE__ ")");
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MinuitParameter.h:51:4
    t.constructor<unsigned int, const std::string &, double, double>(/*finalize=*/jlcxx::finalize_policy::yes);


    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MinuitParameter::MinuitParameter(unsigned int, const std::string &, double, double, double, double) (" __HERE__ ")");
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MinuitParameter.h:58:4
    t.constructor<unsigned int, const std::string &, double, double, double, double>(/*finalize=*/jlcxx::finalize_policy::yes);


    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MinuitParameter::MinuitParameter(const ROOT::Minuit2::MinuitParameter &) (" __HERE__ ")");
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MinuitParameter.h:71:4
    t.constructor<const ROOT::Minuit2::MinuitParameter &>(/*finalize=*/jlcxx::finalize_policy::yes);

    DEBUG_MSG("Adding wrapper for ROOT::Minuit2::MinuitParameter & ROOT::Minuit2::MinuitParameter::operator=(const ROOT::Minuit2::MinuitParameter &) (" __HERE__ ")");
    // signature to use in the veto list: ROOT::Minuit2::MinuitParameter & ROOT::Minuit2::MinuitParameter::operator=(const ROOT::Minuit2::MinuitParameter &)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MinuitParameter.h:78:21
    t.method("assign", static_cast<ROOT::Minuit2::MinuitParameter & (ROOT::Minuit2::MinuitParameter::*)(const ROOT::Minuit2::MinuitParameter &) >(&ROOT::Minuit2::MinuitParameter::operator=));

    DEBUG_MSG("Adding wrapper for unsigned int ROOT::Minuit2::MinuitParameter::Number() (" __HERE__ ")");
    // signature to use in the veto list: unsigned int ROOT::Minuit2::MinuitParameter::Number()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MinuitParameter.h:96:17
    t.method("Number", static_cast<unsigned int (ROOT::Minuit2::MinuitParameter::*)()  const>(&ROOT::Minuit2::MinuitParameter::Number));

    DEBUG_MSG("Adding wrapper for const std::string & ROOT::Minuit2::MinuitParameter::GetName() (" __HERE__ ")");
    // signature to use in the veto list: const std::string & ROOT::Minuit2::MinuitParameter::GetName()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MinuitParameter.h:98:23
    t.method("GetName", static_cast<const std::string & (ROOT::Minuit2::MinuitParameter::*)()  const>(&ROOT::Minuit2::MinuitParameter::GetName));

    DEBUG_MSG("Adding wrapper for const char * ROOT::Minuit2::MinuitParameter::Name() (" __HERE__ ")");
    // signature to use in the veto list: const char * ROOT::Minuit2::MinuitParameter::Name()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MinuitParameter.h:100:16
    t.method("Name", [](ROOT::Minuit2::MinuitParameter const& a) { return (std::string)a.Name(); });
    t.method("Name", [](ROOT::Minuit2::MinuitParameter const* a) { return (std::string)a->Name(); });

    DEBUG_MSG("Adding wrapper for double ROOT::Minuit2::MinuitParameter::Value() (" __HERE__ ")");
    // signature to use in the veto list: double ROOT::Minuit2::MinuitParameter::Value()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MinuitParameter.h:102:11
    t.method("Value", static_cast<double (ROOT::Minuit2::MinuitParameter::*)()  const>(&ROOT::Minuit2::MinuitParameter::Value));

    DEBUG_MSG("Adding wrapper for double ROOT::Minuit2::MinuitParameter::Error() (" __HERE__ ")");
    // signature to use in the veto list: double ROOT::Minuit2::MinuitParameter::Error()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MinuitParameter.h:103:11
    t.method("Error", static_cast<double (ROOT::Minuit2::MinuitParameter::*)()  const>(&ROOT::Minuit2::MinuitParameter::Error));

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MinuitParameter::SetName(const std::string &) (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MinuitParameter::SetName(const std::string &)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MinuitParameter.h:106:9
    t.method("SetName", static_cast<void (ROOT::Minuit2::MinuitParameter::*)(const std::string &) >(&ROOT::Minuit2::MinuitParameter::SetName));

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MinuitParameter::SetValue(double) (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MinuitParameter::SetValue(double)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MinuitParameter.h:108:9
    t.method("SetValue", static_cast<void (ROOT::Minuit2::MinuitParameter::*)(double) >(&ROOT::Minuit2::MinuitParameter::SetValue));

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MinuitParameter::SetError(double) (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MinuitParameter::SetError(double)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MinuitParameter.h:109:9
    t.method("SetError", static_cast<void (ROOT::Minuit2::MinuitParameter::*)(double) >(&ROOT::Minuit2::MinuitParameter::SetError));

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MinuitParameter::SetLimits(double, double) (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MinuitParameter::SetLimits(double, double)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MinuitParameter.h:110:9
    t.method("SetLimits", static_cast<void (ROOT::Minuit2::MinuitParameter::*)(double, double) >(&ROOT::Minuit2::MinuitParameter::SetLimits));

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MinuitParameter::SetUpperLimit(double) (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MinuitParameter::SetUpperLimit(double)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MinuitParameter.h:123:9
    t.method("SetUpperLimit", static_cast<void (ROOT::Minuit2::MinuitParameter::*)(double) >(&ROOT::Minuit2::MinuitParameter::SetUpperLimit));

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MinuitParameter::SetLowerLimit(double) (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MinuitParameter::SetLowerLimit(double)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MinuitParameter.h:131:9
    t.method("SetLowerLimit", static_cast<void (ROOT::Minuit2::MinuitParameter::*)(double) >(&ROOT::Minuit2::MinuitParameter::SetLowerLimit));

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MinuitParameter::RemoveLimits() (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MinuitParameter::RemoveLimits()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MinuitParameter.h:139:9
    t.method("RemoveLimits", static_cast<void (ROOT::Minuit2::MinuitParameter::*)() >(&ROOT::Minuit2::MinuitParameter::RemoveLimits));

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MinuitParameter::Fix() (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MinuitParameter::Fix()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MinuitParameter.h:147:9
    t.method("Fix", static_cast<void (ROOT::Minuit2::MinuitParameter::*)() >(&ROOT::Minuit2::MinuitParameter::Fix));

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MinuitParameter::Release() (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MinuitParameter::Release()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MinuitParameter.h:148:9
    t.method("Release", static_cast<void (ROOT::Minuit2::MinuitParameter::*)() >(&ROOT::Minuit2::MinuitParameter::Release));

    DEBUG_MSG("Adding wrapper for bool ROOT::Minuit2::MinuitParameter::IsConst() (" __HERE__ ")");
    // signature to use in the veto list: bool ROOT::Minuit2::MinuitParameter::IsConst()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MinuitParameter.h:151:9
    t.method("IsConst", static_cast<bool (ROOT::Minuit2::MinuitParameter::*)()  const>(&ROOT::Minuit2::MinuitParameter::IsConst));

    DEBUG_MSG("Adding wrapper for bool ROOT::Minuit2::MinuitParameter::IsFixed() (" __HERE__ ")");
    // signature to use in the veto list: bool ROOT::Minuit2::MinuitParameter::IsFixed()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MinuitParameter.h:152:9
    t.method("IsFixed", static_cast<bool (ROOT::Minuit2::MinuitParameter::*)()  const>(&ROOT::Minuit2::MinuitParameter::IsFixed));

    DEBUG_MSG("Adding wrapper for bool ROOT::Minuit2::MinuitParameter::HasLimits() (" __HERE__ ")");
    // signature to use in the veto list: bool ROOT::Minuit2::MinuitParameter::HasLimits()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MinuitParameter.h:154:9
    t.method("HasLimits", static_cast<bool (ROOT::Minuit2::MinuitParameter::*)()  const>(&ROOT::Minuit2::MinuitParameter::HasLimits));

    DEBUG_MSG("Adding wrapper for bool ROOT::Minuit2::MinuitParameter::HasLowerLimit() (" __HERE__ ")");
    // signature to use in the veto list: bool ROOT::Minuit2::MinuitParameter::HasLowerLimit()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MinuitParameter.h:155:9
    t.method("HasLowerLimit", static_cast<bool (ROOT::Minuit2::MinuitParameter::*)()  const>(&ROOT::Minuit2::MinuitParameter::HasLowerLimit));

    DEBUG_MSG("Adding wrapper for bool ROOT::Minuit2::MinuitParameter::HasUpperLimit() (" __HERE__ ")");
    // signature to use in the veto list: bool ROOT::Minuit2::MinuitParameter::HasUpperLimit()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MinuitParameter.h:156:9
    t.method("HasUpperLimit", static_cast<bool (ROOT::Minuit2::MinuitParameter::*)()  const>(&ROOT::Minuit2::MinuitParameter::HasUpperLimit));

    DEBUG_MSG("Adding wrapper for double ROOT::Minuit2::MinuitParameter::LowerLimit() (" __HERE__ ")");
    // signature to use in the veto list: double ROOT::Minuit2::MinuitParameter::LowerLimit()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MinuitParameter.h:157:11
    t.method("LowerLimit", static_cast<double (ROOT::Minuit2::MinuitParameter::*)()  const>(&ROOT::Minuit2::MinuitParameter::LowerLimit));

    DEBUG_MSG("Adding wrapper for double ROOT::Minuit2::MinuitParameter::UpperLimit() (" __HERE__ ")");
    // signature to use in the veto list: double ROOT::Minuit2::MinuitParameter::UpperLimit()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MinuitParameter.h:158:11
    t.method("UpperLimit", static_cast<double (ROOT::Minuit2::MinuitParameter::*)()  const>(&ROOT::Minuit2::MinuitParameter::UpperLimit));
  }

private:
  std::unique_ptr<jlcxx::TypeWrapper<ROOT::Minuit2::MinuitParameter>> type_;
};
std::shared_ptr<Wrapper> newJlROOT_Minuit2_MinuitParameter(jlcxx::Module& module){
  return std::shared_ptr<Wrapper>(new JlROOT_Minuit2_MinuitParameter(module));
}
