// this file was auto-generated by wrapit 5168a24-dirty
#include "Wrapper.h"

#include "jlMinuit2.h"
#include "dbg_msg.h"
#include "jlcxx/functions.hpp"
#include "jlcxx/stl.hpp"

namespace jlcxx {
  template<> struct IsMirroredType<ROOT::Minuit2::MinimumState> : std::false_type { };
  template<> struct DefaultConstructible<ROOT::Minuit2::MinimumState> : std::false_type { };
}

// Class generating the wrapper for type ROOT::Minuit2::MinimumState
// signature to use in the veto file: ROOT::Minuit2::MinimumState
struct JlROOT_Minuit2_MinimumState: public Wrapper {

  JlROOT_Minuit2_MinimumState(jlcxx::Module& jlModule): Wrapper(jlModule){
    DEBUG_MSG("Adding wrapper for type ROOT::Minuit2::MinimumState (" __HERE__ ")");
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MinimumState.h:27:7
    jlcxx::TypeWrapper<ROOT::Minuit2::MinimumState>  t = jlModule.add_type<ROOT::Minuit2::MinimumState>("ROOT!Minuit2!MinimumState");
    type_ = std::unique_ptr<jlcxx::TypeWrapper<ROOT::Minuit2::MinimumState>>(new jlcxx::TypeWrapper<ROOT::Minuit2::MinimumState>(jlModule, t));
  }

  void add_methods() const{
    auto& t = *type_;


    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MinimumState::MinimumState(unsigned int) (" __HERE__ ")");
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MinimumState.h:31:4
    t.constructor<unsigned int>(/*finalize=*/jlcxx::finalize_policy::yes);


    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MinimumState::MinimumState(double, double, int) (" __HERE__ ")");
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MinimumState.h:37:4
    t.constructor<double, double, int>(/*finalize=*/jlcxx::finalize_policy::yes);


    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MinimumState::MinimumState(const ROOT::Minuit2::MinimumParameters &, double, int) (" __HERE__ ")");
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MinimumState.h:45:4
    t.constructor<const ROOT::Minuit2::MinimumParameters &, double, int>(/*finalize=*/jlcxx::finalize_policy::yes);


    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MinimumState::MinimumState(const ROOT::Minuit2::MinimumParameters &, const ROOT::Minuit2::MinimumError &, const ROOT::Minuit2::FunctionGradient &, double, int) (" __HERE__ ")");
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MinimumState.h:51:4
    t.constructor<const ROOT::Minuit2::MinimumParameters &, const ROOT::Minuit2::MinimumError &, const ROOT::Minuit2::FunctionGradient &, double, int>(/*finalize=*/jlcxx::finalize_policy::yes);

    DEBUG_MSG("Adding wrapper for const ROOT::Minuit2::MinimumParameters & ROOT::Minuit2::MinimumState::Parameters() (" __HERE__ ")");
    // signature to use in the veto list: const ROOT::Minuit2::MinimumParameters & ROOT::Minuit2::MinimumState::Parameters()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MinimumState.h:57:29
    t.method("Parameters", static_cast<const ROOT::Minuit2::MinimumParameters & (ROOT::Minuit2::MinimumState::*)()  const>(&ROOT::Minuit2::MinimumState::Parameters));

    DEBUG_MSG("Adding wrapper for const ROOT::Minuit2::MnAlgebraicVector & ROOT::Minuit2::MinimumState::Vec() (" __HERE__ ")");
    // signature to use in the veto list: const ROOT::Minuit2::MnAlgebraicVector & ROOT::Minuit2::MinimumState::Vec()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MinimumState.h:58:29
    t.method("Vec", static_cast<const ROOT::Minuit2::MnAlgebraicVector & (ROOT::Minuit2::MinimumState::*)()  const>(&ROOT::Minuit2::MinimumState::Vec));

    DEBUG_MSG("Adding wrapper for int ROOT::Minuit2::MinimumState::size() (" __HERE__ ")");
    // signature to use in the veto list: int ROOT::Minuit2::MinimumState::size()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MinimumState.h:59:8
    t.method("size", static_cast<int (ROOT::Minuit2::MinimumState::*)()  const>(&ROOT::Minuit2::MinimumState::size));

    DEBUG_MSG("Adding wrapper for const ROOT::Minuit2::MinimumError & ROOT::Minuit2::MinimumState::Error() (" __HERE__ ")");
    // signature to use in the veto list: const ROOT::Minuit2::MinimumError & ROOT::Minuit2::MinimumState::Error()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MinimumState.h:61:24
    t.method("Error", static_cast<const ROOT::Minuit2::MinimumError & (ROOT::Minuit2::MinimumState::*)()  const>(&ROOT::Minuit2::MinimumState::Error));

    DEBUG_MSG("Adding wrapper for const ROOT::Minuit2::FunctionGradient & ROOT::Minuit2::MinimumState::Gradient() (" __HERE__ ")");
    // signature to use in the veto list: const ROOT::Minuit2::FunctionGradient & ROOT::Minuit2::MinimumState::Gradient()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MinimumState.h:62:28
    t.method("Gradient", static_cast<const ROOT::Minuit2::FunctionGradient & (ROOT::Minuit2::MinimumState::*)()  const>(&ROOT::Minuit2::MinimumState::Gradient));

    DEBUG_MSG("Adding wrapper for double ROOT::Minuit2::MinimumState::Fval() (" __HERE__ ")");
    // signature to use in the veto list: double ROOT::Minuit2::MinimumState::Fval()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MinimumState.h:63:11
    t.method("Fval", static_cast<double (ROOT::Minuit2::MinimumState::*)()  const>(&ROOT::Minuit2::MinimumState::Fval));

    DEBUG_MSG("Adding wrapper for double ROOT::Minuit2::MinimumState::Edm() (" __HERE__ ")");
    // signature to use in the veto list: double ROOT::Minuit2::MinimumState::Edm()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MinimumState.h:64:11
    t.method("Edm", static_cast<double (ROOT::Minuit2::MinimumState::*)()  const>(&ROOT::Minuit2::MinimumState::Edm));

    DEBUG_MSG("Adding wrapper for int ROOT::Minuit2::MinimumState::NFcn() (" __HERE__ ")");
    // signature to use in the veto list: int ROOT::Minuit2::MinimumState::NFcn()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MinimumState.h:65:8
    t.method("NFcn", static_cast<int (ROOT::Minuit2::MinimumState::*)()  const>(&ROOT::Minuit2::MinimumState::NFcn));

    DEBUG_MSG("Adding wrapper for bool ROOT::Minuit2::MinimumState::IsValid() (" __HERE__ ")");
    // signature to use in the veto list: bool ROOT::Minuit2::MinimumState::IsValid()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MinimumState.h:67:9
    t.method("IsValid", static_cast<bool (ROOT::Minuit2::MinimumState::*)()  const>(&ROOT::Minuit2::MinimumState::IsValid));

    DEBUG_MSG("Adding wrapper for bool ROOT::Minuit2::MinimumState::HasParameters() (" __HERE__ ")");
    // signature to use in the veto list: bool ROOT::Minuit2::MinimumState::HasParameters()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MinimumState.h:77:9
    t.method("HasParameters", static_cast<bool (ROOT::Minuit2::MinimumState::*)()  const>(&ROOT::Minuit2::MinimumState::HasParameters));

    DEBUG_MSG("Adding wrapper for bool ROOT::Minuit2::MinimumState::HasCovariance() (" __HERE__ ")");
    // signature to use in the veto list: bool ROOT::Minuit2::MinimumState::HasCovariance()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MinimumState.h:78:9
    t.method("HasCovariance", static_cast<bool (ROOT::Minuit2::MinimumState::*)()  const>(&ROOT::Minuit2::MinimumState::HasCovariance));
  }

private:
  std::unique_ptr<jlcxx::TypeWrapper<ROOT::Minuit2::MinimumState>> type_;
};
std::shared_ptr<Wrapper> newJlROOT_Minuit2_MinimumState(jlcxx::Module& module){
  return std::shared_ptr<Wrapper>(new JlROOT_Minuit2_MinimumState(module));
}
