// this file was auto-generated by wrapit 5168a24-dirty
#include "Wrapper.h"

#include "jlMinuit2.h"
#include "dbg_msg.h"
#include "jlcxx/functions.hpp"
#include "jlcxx/stl.hpp"

namespace jlcxx {
  template<> struct IsMirroredType<ROOT::Minuit2::MnPrint> : std::false_type { };
  template<> struct DefaultConstructible<ROOT::Minuit2::MnPrint> : std::false_type { };
}

// Class generating the wrapper for type ROOT::Minuit2::MnPrint
// signature to use in the veto file: ROOT::Minuit2::MnPrint
struct JlROOT_Minuit2_MnPrint: public Wrapper {

  JlROOT_Minuit2_MnPrint(jlcxx::Module& jlModule): Wrapper(jlModule){
    DEBUG_MSG("Adding wrapper for type ROOT::Minuit2::MnPrint (" __HERE__ ")");
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnPrint.h:73:7
    jlcxx::TypeWrapper<ROOT::Minuit2::MnPrint>  t = jlModule.add_type<ROOT::Minuit2::MnPrint>("ROOT!Minuit2!MnPrint");
    type_ = std::unique_ptr<jlcxx::TypeWrapper<ROOT::Minuit2::MnPrint>>(new jlcxx::TypeWrapper<ROOT::Minuit2::MnPrint>(jlModule, t));
  }

  void add_methods() const{
    auto& t = *type_;


    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnPrint::MnPrint(const char *, int) (" __HERE__ ")");
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnPrint.h:99:4
    t.constructor<const char *>(/*finalize=*/jlcxx::finalize_policy::yes);
    t.constructor<const char *, int>(/*finalize=*/jlcxx::finalize_policy::yes);

    DEBUG_MSG("Adding wrapper for int ROOT::Minuit2::MnPrint::SetGlobalLevel(int) (" __HERE__ ")");
    // signature to use in the veto list: int ROOT::Minuit2::MnPrint::SetGlobalLevel(int)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnPrint.h:103:15
    module_.method("ROOT!Minuit2!MnPrint!SetGlobalLevel", static_cast<int (*)(int) >(&ROOT::Minuit2::MnPrint::SetGlobalLevel));

    DEBUG_MSG("Adding wrapper for int ROOT::Minuit2::MnPrint::GlobalLevel() (" __HERE__ ")");
    // signature to use in the veto list: int ROOT::Minuit2::MnPrint::GlobalLevel()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnPrint.h:106:15
    module_.method("ROOT!Minuit2!MnPrint!GlobalLevel", static_cast<int (*)() >(&ROOT::Minuit2::MnPrint::GlobalLevel));

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnPrint::ShowPrefixStack(bool) (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MnPrint::ShowPrefixStack(bool)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnPrint.h:109:16
    module_.method("ROOT!Minuit2!MnPrint!ShowPrefixStack", static_cast<void (*)(bool) >(&ROOT::Minuit2::MnPrint::ShowPrefixStack));

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnPrint::AddFilter(const char *) (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MnPrint::AddFilter(const char *)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnPrint.h:111:16
    module_.method("ROOT!Minuit2!MnPrint!AddFilter", static_cast<void (*)(const char *) >(&ROOT::Minuit2::MnPrint::AddFilter));

    DEBUG_MSG("Adding wrapper for void ROOT::Minuit2::MnPrint::ClearFilter() (" __HERE__ ")");
    // signature to use in the veto list: void ROOT::Minuit2::MnPrint::ClearFilter()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnPrint.h:112:16
    module_.method("ROOT!Minuit2!MnPrint!ClearFilter", static_cast<void (*)() >(&ROOT::Minuit2::MnPrint::ClearFilter));

    DEBUG_MSG("Adding wrapper for int ROOT::Minuit2::MnPrint::SetMaxNP(int) (" __HERE__ ")");
    // signature to use in the veto list: int ROOT::Minuit2::MnPrint::SetMaxNP(int)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnPrint.h:117:15
    module_.method("ROOT!Minuit2!MnPrint!SetMaxNP", static_cast<int (*)(int) >(&ROOT::Minuit2::MnPrint::SetMaxNP));

    DEBUG_MSG("Adding wrapper for int ROOT::Minuit2::MnPrint::MaxNP() (" __HERE__ ")");
    // signature to use in the veto list: int ROOT::Minuit2::MnPrint::MaxNP()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnPrint.h:120:15
    module_.method("ROOT!Minuit2!MnPrint!MaxNP", static_cast<int (*)() >(&ROOT::Minuit2::MnPrint::MaxNP));

    DEBUG_MSG("Adding wrapper for int ROOT::Minuit2::MnPrint::SetLevel(int) (" __HERE__ ")");
    // signature to use in the veto list: int ROOT::Minuit2::MnPrint::SetLevel(int)
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnPrint.h:123:8
    t.method("SetLevel", static_cast<int (ROOT::Minuit2::MnPrint::*)(int) >(&ROOT::Minuit2::MnPrint::SetLevel));

    DEBUG_MSG("Adding wrapper for int ROOT::Minuit2::MnPrint::Level() (" __HERE__ ")");
    // signature to use in the veto list: int ROOT::Minuit2::MnPrint::Level()
    // defined in /Users/mato/.julia/artifacts/4afa81fd17c8d2616a0895f609579f19a4e4e4b7/include/Minuit2/Minuit2/MnPrint.h:126:8
    t.method("Level", static_cast<int (ROOT::Minuit2::MnPrint::*)()  const>(&ROOT::Minuit2::MnPrint::Level));
  }

private:
  std::unique_ptr<jlcxx::TypeWrapper<ROOT::Minuit2::MnPrint>> type_;
};
std::shared_ptr<Wrapper> newJlROOT_Minuit2_MnPrint(jlcxx::Module& module){
  return std::shared_ptr<Wrapper>(new JlROOT_Minuit2_MnPrint(module));
}
